// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package gosdk

type Accounting struct {
	Accounts           *PanoraAccounts
	Addresses          *Addresses
	Attachments        *PanoraAttachments
	Balancesheets      *Balancesheets
	Cashflowstatements *Cashflowstatements
	Companyinfos       *Companyinfos
	Contacts           *PanoraAccountingContacts
	Creditnotes        *Creditnotes
	Expenses           *Expenses
	Incomestatements   *Incomestatements
	Invoices           *Invoices
	Items              *Items
	Journalentries     *Journalentries
	Payments           *Payments
	Phonenumbers       *Phonenumbers
	Purchaseorders     *Purchaseorders
	Taxrates           *Taxrates
	Trackingcategories *Trackingcategories
	Transactions       *Transactions
	Vendorcredits      *Vendorcredits

	sdkConfiguration sdkConfiguration
}

func newAccounting(sdkConfig sdkConfiguration) *Accounting {
	return &Accounting{
		sdkConfiguration:   sdkConfig,
		Accounts:           newPanoraAccounts(sdkConfig),
		Addresses:          newAddresses(sdkConfig),
		Attachments:        newPanoraAttachments(sdkConfig),
		Balancesheets:      newBalancesheets(sdkConfig),
		Cashflowstatements: newCashflowstatements(sdkConfig),
		Companyinfos:       newCompanyinfos(sdkConfig),
		Contacts:           newPanoraAccountingContacts(sdkConfig),
		Creditnotes:        newCreditnotes(sdkConfig),
		Expenses:           newExpenses(sdkConfig),
		Incomestatements:   newIncomestatements(sdkConfig),
		Invoices:           newInvoices(sdkConfig),
		Items:              newItems(sdkConfig),
		Journalentries:     newJournalentries(sdkConfig),
		Payments:           newPayments(sdkConfig),
		Phonenumbers:       newPhonenumbers(sdkConfig),
		Purchaseorders:     newPurchaseorders(sdkConfig),
		Taxrates:           newTaxrates(sdkConfig),
		Trackingcategories: newTrackingcategories(sdkConfig),
		Transactions:       newTransactions(sdkConfig),
		Vendorcredits:      newVendorcredits(sdkConfig),
	}
}
