// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package gosdk

type Filestorage struct {
	Files   *Files
	Folders *Folders
	Groups  *Groups
	Users   *PanoraFilestorageUsers

	sdkConfiguration sdkConfiguration
}

func newFilestorage(sdkConfig sdkConfiguration) *Filestorage {
	return &Filestorage{
		sdkConfiguration: sdkConfig,
		Files:            newFiles(sdkConfig),
		Folders:          newFolders(sdkConfig),
		Groups:           newGroups(sdkConfig),
		Users:            newPanoraFilestorageUsers(sdkConfig),
	}
}
