// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package gosdk

type Hris struct {
	Bankinfos           *Bankinfos
	Benefits            *Benefits
	Companies           *PanoraCompanies
	Dependents          *Dependents
	Employeepayrollruns *Employeepayrollruns
	Employees           *Employees
	Employerbenefits    *Employerbenefits
	Employments         *Employments
	Groups              *Groups
	Locations           *Locations
	Paygroups           *Paygroups
	Payrollruns         *Payrollruns
	Timeoffs            *Timeoffs
	Timeoffbalances     *Timeoffbalances
	Timesheetentries    *Timesheetentries

	sdkConfiguration sdkConfiguration
}

func newHris(sdkConfig sdkConfiguration) *Hris {
	return &Hris{
		sdkConfiguration:    sdkConfig,
		Bankinfos:           newBankinfos(sdkConfig),
		Benefits:            newBenefits(sdkConfig),
		Companies:           newPanoraCompanies(sdkConfig),
		Dependents:          newDependents(sdkConfig),
		Employeepayrollruns: newEmployeepayrollruns(sdkConfig),
		Employees:           newEmployees(sdkConfig),
		Employerbenefits:    newEmployerbenefits(sdkConfig),
		Employments:         newEmployments(sdkConfig),
		Groups:              newGroups(sdkConfig),
		Locations:           newLocations(sdkConfig),
		Paygroups:           newPaygroups(sdkConfig),
		Payrollruns:         newPayrollruns(sdkConfig),
		Timeoffs:            newTimeoffs(sdkConfig),
		Timeoffbalances:     newTimeoffbalances(sdkConfig),
		Timesheetentries:    newTimesheetentries(sdkConfig),
	}
}
