// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package gosdk

type Marketingautomation struct {
	Actions     *Actions
	Automations *Automations
	Campaigns   *Campaigns
	Contacts    *PanoraMarketingautomationContacts
	Emails      *Emails
	Events      *Events
	Lists       *Lists
	Messages    *Messages
	Templates   *Templates
	Users       *PanoraMarketingautomationUsers

	sdkConfiguration sdkConfiguration
}

func newMarketingautomation(sdkConfig sdkConfiguration) *Marketingautomation {
	return &Marketingautomation{
		sdkConfiguration: sdkConfig,
		Actions:          newActions(sdkConfig),
		Automations:      newAutomations(sdkConfig),
		Campaigns:        newCampaigns(sdkConfig),
		Contacts:         newPanoraMarketingautomationContacts(sdkConfig),
		Emails:           newEmails(sdkConfig),
		Events:           newEvents(sdkConfig),
		Lists:            newLists(sdkConfig),
		Messages:         newMessages(sdkConfig),
		Templates:        newTemplates(sdkConfig),
		Users:            newPanoraMarketingautomationUsers(sdkConfig),
	}
}
