// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateAtsInterviewRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Ats software.
	RemoteData               *bool                               `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedAtsInterviewInput components.UnifiedAtsInterviewInput `request:"mediaType=application/json"`
}

func (o *CreateAtsInterviewRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateAtsInterviewRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateAtsInterviewRequest) GetUnifiedAtsInterviewInput() components.UnifiedAtsInterviewInput {
	if o == nil {
		return components.UnifiedAtsInterviewInput{}
	}
	return o.UnifiedAtsInterviewInput
}

type CreateAtsInterviewResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	UnifiedAtsInterviewOutput *components.UnifiedAtsInterviewOutput
}

func (o *CreateAtsInterviewResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAtsInterviewResponse) GetUnifiedAtsInterviewOutput() *components.UnifiedAtsInterviewOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAtsInterviewOutput
}
