// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateCrmContactRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original CRM software.
	RemoteData             *bool                             `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedCrmContactInput components.UnifiedCrmContactInput `request:"mediaType=application/json"`
}

func (o *CreateCrmContactRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateCrmContactRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateCrmContactRequest) GetUnifiedCrmContactInput() components.UnifiedCrmContactInput {
	if o == nil {
		return components.UnifiedCrmContactInput{}
	}
	return o.UnifiedCrmContactInput
}

type CreateCrmContactResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	UnifiedCrmContactOutput *components.UnifiedCrmContactOutput
}

func (o *CreateCrmContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCrmContactResponse) GetUnifiedCrmContactOutput() *components.UnifiedCrmContactOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedCrmContactOutput
}
