// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateEcommerceProductRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Accounting software.
	RemoteData                   *bool                                   `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedEcommerceProductInput components.UnifiedEcommerceProductInput `request:"mediaType=application/json"`
}

func (o *CreateEcommerceProductRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateEcommerceProductRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateEcommerceProductRequest) GetUnifiedEcommerceProductInput() components.UnifiedEcommerceProductInput {
	if o == nil {
		return components.UnifiedEcommerceProductInput{}
	}
	return o.UnifiedEcommerceProductInput
}

type CreateEcommerceProductResponse struct {
	HTTPMeta                      components.HTTPMetadata `json:"-"`
	UnifiedEcommerceProductOutput *components.UnifiedEcommerceProductOutput
}

func (o *CreateEcommerceProductResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEcommerceProductResponse) GetUnifiedEcommerceProductOutput() *components.UnifiedEcommerceProductOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedEcommerceProductOutput
}
