// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateProjectResponse struct {
	HTTPMeta        components.HTTPMetadata `json:"-"`
	ProjectResponse *components.ProjectResponse
}

func (o *CreateProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateProjectResponse) GetProjectResponse() *components.ProjectResponse {
	if o == nil {
		return nil
	}
	return o.ProjectResponse
}
