// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateMarketingautomationTemplateRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Marketingautomation software.
	RemoteData                              *bool                                              `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedMarketingautomationTemplateInput components.UnifiedMarketingautomationTemplateInput `request:"mediaType=application/json"`
}

func (o *CreateMarketingautomationTemplateRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateMarketingautomationTemplateRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateMarketingautomationTemplateRequest) GetUnifiedMarketingautomationTemplateInput() components.UnifiedMarketingautomationTemplateInput {
	if o == nil {
		return components.UnifiedMarketingautomationTemplateInput{}
	}
	return o.UnifiedMarketingautomationTemplateInput
}

type CreateMarketingautomationTemplateResponse struct {
	HTTPMeta                                 components.HTTPMetadata `json:"-"`
	UnifiedMarketingautomationTemplateOutput *components.UnifiedMarketingautomationTemplateOutput
}

func (o *CreateMarketingautomationTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateMarketingautomationTemplateResponse) GetUnifiedMarketingautomationTemplateOutput() *components.UnifiedMarketingautomationTemplateOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedMarketingautomationTemplateOutput
}
