// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateAtsActivityRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Ats software.
	RemoteData              *bool                              `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedAtsActivityInput components.UnifiedAtsActivityInput `request:"mediaType=application/json"`
}

func (o *CreateAtsActivityRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateAtsActivityRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateAtsActivityRequest) GetUnifiedAtsActivityInput() components.UnifiedAtsActivityInput {
	if o == nil {
		return components.UnifiedAtsActivityInput{}
	}
	return o.UnifiedAtsActivityInput
}

type CreateAtsActivityResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	UnifiedAtsActivityOutput *components.UnifiedAtsActivityOutput
}

func (o *CreateAtsActivityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAtsActivityResponse) GetUnifiedAtsActivityOutput() *components.UnifiedAtsActivityOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAtsActivityOutput
}
