// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateMarketingautomationAutomationRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Marketingautomation software.
	RemoteData                                *bool                                                `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedMarketingautomationAutomationInput components.UnifiedMarketingautomationAutomationInput `request:"mediaType=application/json"`
}

func (o *CreateMarketingautomationAutomationRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateMarketingautomationAutomationRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateMarketingautomationAutomationRequest) GetUnifiedMarketingautomationAutomationInput() components.UnifiedMarketingautomationAutomationInput {
	if o == nil {
		return components.UnifiedMarketingautomationAutomationInput{}
	}
	return o.UnifiedMarketingautomationAutomationInput
}

type CreateMarketingautomationAutomationResponse struct {
	HTTPMeta                                   components.HTTPMetadata `json:"-"`
	UnifiedMarketingautomationAutomationOutput *components.UnifiedMarketingautomationAutomationOutput
}

func (o *CreateMarketingautomationAutomationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateMarketingautomationAutomationResponse) GetUnifiedMarketingautomationAutomationOutput() *components.UnifiedMarketingautomationAutomationOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedMarketingautomationAutomationOutput
}
