// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateAtsCandidateRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Ats software.
	RemoteData               *bool                               `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedAtsCandidateInput components.UnifiedAtsCandidateInput `request:"mediaType=application/json"`
}

func (o *CreateAtsCandidateRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateAtsCandidateRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateAtsCandidateRequest) GetUnifiedAtsCandidateInput() components.UnifiedAtsCandidateInput {
	if o == nil {
		return components.UnifiedAtsCandidateInput{}
	}
	return o.UnifiedAtsCandidateInput
}

type CreateAtsCandidateResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	UnifiedAtsCandidateOutput *components.UnifiedAtsCandidateOutput
}

func (o *CreateAtsCandidateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAtsCandidateResponse) GetUnifiedAtsCandidateOutput() *components.UnifiedAtsCandidateOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAtsCandidateOutput
}
