// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type CreateAccountingExpenseRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original Accounting software.
	RemoteData                    *bool                                    `queryParam:"style=form,explode=true,name=remote_data"`
	UnifiedAccountingExpenseInput components.UnifiedAccountingExpenseInput `request:"mediaType=application/json"`
}

func (o *CreateAccountingExpenseRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *CreateAccountingExpenseRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *CreateAccountingExpenseRequest) GetUnifiedAccountingExpenseInput() components.UnifiedAccountingExpenseInput {
	if o == nil {
		return components.UnifiedAccountingExpenseInput{}
	}
	return o.UnifiedAccountingExpenseInput
}

type CreateAccountingExpenseResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	UnifiedAccountingExpenseOutput *components.UnifiedAccountingExpenseOutput
}

func (o *CreateAccountingExpenseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAccountingExpenseResponse) GetUnifiedAccountingExpenseOutput() *components.UnifiedAccountingExpenseOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAccountingExpenseOutput
}
