// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type DefinitionsResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	CustomFieldResponse *components.CustomFieldResponse
}

func (o *DefinitionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DefinitionsResponse) GetCustomFieldResponse() *components.CustomFieldResponse {
	if o == nil {
		return nil
	}
	return o.CustomFieldResponse
}
