// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type GetPanoraCoreEventsRequest struct {
	Page  *float64 `queryParam:"style=form,explode=true,name=page"`
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
}

func (o *GetPanoraCoreEventsRequest) GetPage() *float64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetPanoraCoreEventsRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type GetPanoraCoreEventsResponse struct {
	HTTPMeta       components.HTTPMetadata `json:"-"`
	EventResponses []components.EventResponse
}

func (o *GetPanoraCoreEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPanoraCoreEventsResponse) GetEventResponses() []components.EventResponse {
	if o == nil {
		return nil
	}
	return o.EventResponses
}
