// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type GetProjectsResponse struct {
	HTTPMeta         components.HTTPMetadata `json:"-"`
	ProjectResponses []components.ProjectResponse
}

func (o *GetProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetProjectsResponse) GetProjectResponses() []components.ProjectResponse {
	if o == nil {
		return nil
	}
	return o.ProjectResponses
}
