// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type HealthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Api is healthy
	Number *float64
}

func (o *HealthResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *HealthResponse) GetNumber() *float64 {
	if o == nil {
		return nil
	}
	return o.Number
}
