// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListCrmEngagementsRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *ListCrmEngagementsRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListCrmEngagementsRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListCrmEngagementsRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListCrmEngagementsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListCrmEngagementsResponseBody struct {
	PrevCursor *string                                 `json:"prev_cursor"`
	NextCursor *string                                 `json:"next_cursor"`
	Data       []components.UnifiedCrmEngagementOutput `json:"data"`
}

func (o *ListCrmEngagementsResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListCrmEngagementsResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListCrmEngagementsResponseBody) GetData() []components.UnifiedCrmEngagementOutput {
	if o == nil {
		return []components.UnifiedCrmEngagementOutput{}
	}
	return o.Data
}

type ListCrmEngagementsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListCrmEngagementsResponseBody
}

func (o *ListCrmEngagementsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListCrmEngagementsResponse) GetObject() *ListCrmEngagementsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
