// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListAccountingJournalEntryRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListAccountingJournalEntryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccountingJournalEntryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAccountingJournalEntryRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListAccountingJournalEntryRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListAccountingJournalEntryRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAccountingJournalEntryRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListAccountingJournalEntryResponseBody struct {
	PrevCursor string                                           `json:"prev_cursor"`
	NextCursor string                                           `json:"next_cursor"`
	Data       []components.UnifiedAccountingJournalentryOutput `json:"data"`
}

func (o *ListAccountingJournalEntryResponseBody) GetPrevCursor() string {
	if o == nil {
		return ""
	}
	return o.PrevCursor
}

func (o *ListAccountingJournalEntryResponseBody) GetNextCursor() string {
	if o == nil {
		return ""
	}
	return o.NextCursor
}

func (o *ListAccountingJournalEntryResponseBody) GetData() []components.UnifiedAccountingJournalentryOutput {
	if o == nil {
		return []components.UnifiedAccountingJournalentryOutput{}
	}
	return o.Data
}

type ListAccountingJournalEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAccountingJournalEntryResponseBody
}

func (o *ListAccountingJournalEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAccountingJournalEntryResponse) GetObject() *ListAccountingJournalEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
