// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListAtsUsersRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *ListAtsUsersRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListAtsUsersRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListAtsUsersRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAtsUsersRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListAtsUsersResponseBody struct {
	PrevCursor *string                           `json:"prev_cursor"`
	NextCursor *string                           `json:"next_cursor"`
	Data       []components.UnifiedAtsUserOutput `json:"data"`
}

func (o *ListAtsUsersResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListAtsUsersResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListAtsUsersResponseBody) GetData() []components.UnifiedAtsUserOutput {
	if o == nil {
		return []components.UnifiedAtsUserOutput{}
	}
	return o.Data
}

type ListAtsUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAtsUsersResponseBody
}

func (o *ListAtsUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAtsUsersResponse) GetObject() *ListAtsUsersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
