// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListHrisCompaniesRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListHrisCompaniesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListHrisCompaniesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListHrisCompaniesRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListHrisCompaniesRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListHrisCompaniesRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListHrisCompaniesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListHrisCompaniesResponseBody struct {
	PrevCursor *string                               `json:"prev_cursor"`
	NextCursor *string                               `json:"next_cursor"`
	Data       []components.UnifiedHrisCompanyOutput `json:"data"`
}

func (o *ListHrisCompaniesResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListHrisCompaniesResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListHrisCompaniesResponseBody) GetData() []components.UnifiedHrisCompanyOutput {
	if o == nil {
		return []components.UnifiedHrisCompanyOutput{}
	}
	return o.Data
}

type ListHrisCompaniesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListHrisCompaniesResponseBody

	Next func() (*ListHrisCompaniesResponse, error)
}

func (o *ListHrisCompaniesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListHrisCompaniesResponse) GetObject() *ListHrisCompaniesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
