// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListAccountingExpenseRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListAccountingExpenseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccountingExpenseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAccountingExpenseRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListAccountingExpenseRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListAccountingExpenseRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAccountingExpenseRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListAccountingExpenseResponseBody struct {
	PrevCursor string                                      `json:"prev_cursor"`
	NextCursor string                                      `json:"next_cursor"`
	Data       []components.UnifiedAccountingExpenseOutput `json:"data"`
}

func (o *ListAccountingExpenseResponseBody) GetPrevCursor() string {
	if o == nil {
		return ""
	}
	return o.PrevCursor
}

func (o *ListAccountingExpenseResponseBody) GetNextCursor() string {
	if o == nil {
		return ""
	}
	return o.NextCursor
}

func (o *ListAccountingExpenseResponseBody) GetData() []components.UnifiedAccountingExpenseOutput {
	if o == nil {
		return []components.UnifiedAccountingExpenseOutput{}
	}
	return o.Data
}

type ListAccountingExpenseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAccountingExpenseResponseBody
}

func (o *ListAccountingExpenseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAccountingExpenseResponse) GetObject() *ListAccountingExpenseResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
