// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListHrisBenefitsRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *ListHrisBenefitsRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListHrisBenefitsRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListHrisBenefitsRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListHrisBenefitsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListHrisBenefitsResponseBody struct {
	PrevCursor *string                               `json:"prev_cursor"`
	NextCursor *string                               `json:"next_cursor"`
	Data       []components.UnifiedHrisBenefitOutput `json:"data"`
}

func (o *ListHrisBenefitsResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListHrisBenefitsResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListHrisBenefitsResponseBody) GetData() []components.UnifiedHrisBenefitOutput {
	if o == nil {
		return []components.UnifiedHrisBenefitOutput{}
	}
	return o.Data
}

type ListHrisBenefitsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListHrisBenefitsResponseBody
}

func (o *ListHrisBenefitsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListHrisBenefitsResponse) GetObject() *ListHrisBenefitsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
