// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListAccountingVendorCreditRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListAccountingVendorCreditRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccountingVendorCreditRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAccountingVendorCreditRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListAccountingVendorCreditRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListAccountingVendorCreditRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAccountingVendorCreditRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListAccountingVendorCreditResponseBody struct {
	PrevCursor *string                                          `json:"prev_cursor"`
	NextCursor *string                                          `json:"next_cursor"`
	Data       []components.UnifiedAccountingVendorcreditOutput `json:"data"`
}

func (o *ListAccountingVendorCreditResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListAccountingVendorCreditResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListAccountingVendorCreditResponseBody) GetData() []components.UnifiedAccountingVendorcreditOutput {
	if o == nil {
		return []components.UnifiedAccountingVendorcreditOutput{}
	}
	return o.Data
}

type ListAccountingVendorCreditResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAccountingVendorCreditResponseBody

	Next func() (*ListAccountingVendorCreditResponse, error)
}

func (o *ListAccountingVendorCreditResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAccountingVendorCreditResponse) GetObject() *ListAccountingVendorCreditResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
