// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListHrisEmployeeRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListHrisEmployeeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListHrisEmployeeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListHrisEmployeeRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListHrisEmployeeRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListHrisEmployeeRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListHrisEmployeeRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListHrisEmployeeResponseBody struct {
	PrevCursor string                                 `json:"prev_cursor"`
	NextCursor string                                 `json:"next_cursor"`
	Data       []components.UnifiedHrisEmployeeOutput `json:"data"`
}

func (o *ListHrisEmployeeResponseBody) GetPrevCursor() string {
	if o == nil {
		return ""
	}
	return o.PrevCursor
}

func (o *ListHrisEmployeeResponseBody) GetNextCursor() string {
	if o == nil {
		return ""
	}
	return o.NextCursor
}

func (o *ListHrisEmployeeResponseBody) GetData() []components.UnifiedHrisEmployeeOutput {
	if o == nil {
		return []components.UnifiedHrisEmployeeOutput{}
	}
	return o.Data
}

type ListHrisEmployeeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListHrisEmployeeResponseBody
}

func (o *ListHrisEmployeeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListHrisEmployeeResponse) GetObject() *ListHrisEmployeeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
