// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListCrmTaskRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"30" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListCrmTaskRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCrmTaskRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListCrmTaskRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListCrmTaskRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListCrmTaskRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListCrmTaskRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListCrmTaskResponseBody struct {
	PrevCursor *string                           `json:"prev_cursor"`
	NextCursor *string                           `json:"next_cursor"`
	Data       []components.UnifiedCrmTaskOutput `json:"data"`
}

func (o *ListCrmTaskResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListCrmTaskResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListCrmTaskResponseBody) GetData() []components.UnifiedCrmTaskOutput {
	if o == nil {
		return []components.UnifiedCrmTaskOutput{}
	}
	return o.Data
}

type ListCrmTaskResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListCrmTaskResponseBody

	Next func() (*ListCrmTaskResponse, error)
}

func (o *ListCrmTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListCrmTaskResponse) GetObject() *ListCrmTaskResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
