// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListAccountingPhonenumberRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"30" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListAccountingPhonenumberRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccountingPhonenumberRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAccountingPhonenumberRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListAccountingPhonenumberRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListAccountingPhonenumberRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAccountingPhonenumberRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListAccountingPhonenumberResponseBody struct {
	PrevCursor *string                                         `json:"prev_cursor"`
	NextCursor *string                                         `json:"next_cursor"`
	Data       []components.UnifiedAccountingPhonenumberOutput `json:"data"`
}

func (o *ListAccountingPhonenumberResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListAccountingPhonenumberResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListAccountingPhonenumberResponseBody) GetData() []components.UnifiedAccountingPhonenumberOutput {
	if o == nil {
		return []components.UnifiedAccountingPhonenumberOutput{}
	}
	return o.Data
}

type ListAccountingPhonenumberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAccountingPhonenumberResponseBody

	Next func() (*ListAccountingPhonenumberResponse, error)
}

func (o *ListAccountingPhonenumberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAccountingPhonenumberResponse) GetObject() *ListAccountingPhonenumberResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
