// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"github.com/panoratech/go-sdk/models/components"
)

type ListCrmUsersRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListCrmUsersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCrmUsersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListCrmUsersRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListCrmUsersRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListCrmUsersRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListCrmUsersRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListCrmUsersResponseBody struct {
	PrevCursor string                            `json:"prev_cursor"`
	NextCursor string                            `json:"next_cursor"`
	Data       []components.UnifiedCrmUserOutput `json:"data"`
}

func (o *ListCrmUsersResponseBody) GetPrevCursor() string {
	if o == nil {
		return ""
	}
	return o.PrevCursor
}

func (o *ListCrmUsersResponseBody) GetNextCursor() string {
	if o == nil {
		return ""
	}
	return o.NextCursor
}

func (o *ListCrmUsersResponseBody) GetData() []components.UnifiedCrmUserOutput {
	if o == nil {
		return []components.UnifiedCrmUserOutput{}
	}
	return o.Data
}

type ListCrmUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListCrmUsersResponseBody
}

func (o *ListCrmUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListCrmUsersResponse) GetObject() *ListCrmUsersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
