// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListConnectionsResponse struct {
	HTTPMeta    components.HTTPMetadata `json:"-"`
	Connections []components.Connection
}

func (o *ListConnectionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListConnectionsResponse) GetConnections() []components.Connection {
	if o == nil {
		return nil
	}
	return o.Connections
}
