// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListHrisBankInfoRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *ListHrisBankInfoRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListHrisBankInfoRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListHrisBankInfoRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListHrisBankInfoRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListHrisBankInfoResponseBody struct {
	PrevCursor *string                                `json:"prev_cursor"`
	NextCursor *string                                `json:"next_cursor"`
	Data       []components.UnifiedHrisBankinfoOutput `json:"data"`
}

func (o *ListHrisBankInfoResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListHrisBankInfoResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListHrisBankInfoResponseBody) GetData() []components.UnifiedHrisBankinfoOutput {
	if o == nil {
		return []components.UnifiedHrisBankinfoOutput{}
	}
	return o.Data
}

type ListHrisBankInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListHrisBankInfoResponseBody
}

func (o *ListHrisBankInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListHrisBankInfoResponse) GetObject() *ListHrisBankInfoResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
