// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ListMarketingautomationActionRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// Set to true to include data from the original software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
	// Set to get the number of records.
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Set to get the number of records after this cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *ListMarketingautomationActionRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *ListMarketingautomationActionRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *ListMarketingautomationActionRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListMarketingautomationActionRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListMarketingautomationActionResponseBody struct {
	PrevCursor *string                                             `json:"prev_cursor"`
	NextCursor *string                                             `json:"next_cursor"`
	Data       []components.UnifiedMarketingautomationActionOutput `json:"data"`
}

func (o *ListMarketingautomationActionResponseBody) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

func (o *ListMarketingautomationActionResponseBody) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *ListMarketingautomationActionResponseBody) GetData() []components.UnifiedMarketingautomationActionOutput {
	if o == nil {
		return []components.UnifiedMarketingautomationActionOutput{}
	}
	return o.Data
}

type ListMarketingautomationActionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListMarketingautomationActionResponseBody

	Next func() (*ListMarketingautomationActionResponse, error)
}

func (o *ListMarketingautomationActionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListMarketingautomationActionResponse) GetObject() *ListMarketingautomationActionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
