// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RagControllerQueryEmbeddingsResponseBody struct {
}

type RagControllerQueryEmbeddingsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *RagControllerQueryEmbeddingsResponseBody
}

func (o *RagControllerQueryEmbeddingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RagControllerQueryEmbeddingsResponse) GetObject() *RagControllerQueryEmbeddingsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
