// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RequestRequest struct {
	XConnectionToken      string                           `header:"style=simple,explode=false,name=x-connection-token"`
	PassThroughRequestDto components.PassThroughRequestDto `request:"mediaType=application/json"`
}

func (o *RequestRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RequestRequest) GetPassThroughRequestDto() components.PassThroughRequestDto {
	if o == nil {
		return components.PassThroughRequestDto{}
	}
	return o.PassThroughRequestDto
}

type RequestPassthroughResponseBody struct {
}

type RequestResponseBody struct {
}

type RequestResponse struct {
	HTTPMeta                              components.HTTPMetadata `json:"-"`
	TwoHundredApplicationJSONObject       *RequestResponseBody
	TwoHundredAndOneApplicationJSONObject *RequestPassthroughResponseBody
}

func (o *RequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RequestResponse) GetTwoHundredApplicationJSONObject() *RequestResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *RequestResponse) GetTwoHundredAndOneApplicationJSONObject() *RequestPassthroughResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}
