// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type ResyncResponse struct {
	HTTPMeta        components.HTTPMetadata `json:"-"`
	ResyncStatusDto *components.ResyncStatusDto
}

func (o *ResyncResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ResyncResponse) GetResyncStatusDto() *components.ResyncStatusDto {
	if o == nil {
		return nil
	}
	return o.ResyncStatusDto
}
