// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveMarketingAutomationUserRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the user you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Marketingautomation software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveMarketingAutomationUserRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveMarketingAutomationUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveMarketingAutomationUserRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveMarketingAutomationUserResponse struct {
	HTTPMeta                             components.HTTPMetadata `json:"-"`
	UnifiedMarketingautomationUserOutput *components.UnifiedMarketingautomationUserOutput
}

func (o *RetrieveMarketingAutomationUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveMarketingAutomationUserResponse) GetUnifiedMarketingautomationUserOutput() *components.UnifiedMarketingautomationUserOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedMarketingautomationUserOutput
}
