// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveHrisPayrollRunRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the payroll run you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Hris software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveHrisPayrollRunRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveHrisPayrollRunRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveHrisPayrollRunRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveHrisPayrollRunResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	UnifiedHrisPayrollrunOutput *components.UnifiedHrisPayrollrunOutput
}

func (o *RetrieveHrisPayrollRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveHrisPayrollRunResponse) GetUnifiedHrisPayrollrunOutput() *components.UnifiedHrisPayrollrunOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedHrisPayrollrunOutput
}
