// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveAccountingTrackingCategoryRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the trackingcategory you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Accounting software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveAccountingTrackingCategoryRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveAccountingTrackingCategoryRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveAccountingTrackingCategoryRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveAccountingTrackingCategoryResponse struct {
	HTTPMeta                                components.HTTPMetadata `json:"-"`
	UnifiedAccountingTrackingcategoryOutput *components.UnifiedAccountingTrackingcategoryOutput
}

func (o *RetrieveAccountingTrackingCategoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveAccountingTrackingCategoryResponse) GetUnifiedAccountingTrackingcategoryOutput() *components.UnifiedAccountingTrackingcategoryOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAccountingTrackingcategoryOutput
}
