// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveAtsJobInterviewStageRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the jobinterviewstage you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Ats software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveAtsJobInterviewStageRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveAtsJobInterviewStageRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveAtsJobInterviewStageRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveAtsJobInterviewStageResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	UnifiedAtsJobinterviewstageOutput *components.UnifiedAtsJobinterviewstageOutput
}

func (o *RetrieveAtsJobInterviewStageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveAtsJobInterviewStageResponse) GetUnifiedAtsJobinterviewstageOutput() *components.UnifiedAtsJobinterviewstageOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAtsJobinterviewstageOutput
}
