// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveMarketingAutomationContactRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the contact you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Marketingautomation software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveMarketingAutomationContactRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveMarketingAutomationContactRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveMarketingAutomationContactRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveMarketingAutomationContactResponse struct {
	HTTPMeta                                components.HTTPMetadata `json:"-"`
	UnifiedMarketingautomationContactOutput *components.UnifiedMarketingautomationContactOutput
}

func (o *RetrieveMarketingAutomationContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveMarketingAutomationContactResponse) GetUnifiedMarketingautomationContactOutput() *components.UnifiedMarketingautomationContactOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedMarketingautomationContactOutput
}
