// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveFilestorageFolderRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the folder you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original File Storage software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveFilestorageFolderRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveFilestorageFolderRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveFilestorageFolderRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveFilestorageFolderResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	UnifiedFilestorageFolderOutput *components.UnifiedFilestorageFolderOutput
}

func (o *RetrieveFilestorageFolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveFilestorageFolderResponse) GetUnifiedFilestorageFolderOutput() *components.UnifiedFilestorageFolderOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedFilestorageFolderOutput
}
