// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveHrisBankInfoRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the bank info you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Hris software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveHrisBankInfoRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveHrisBankInfoRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveHrisBankInfoRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveHrisBankInfoResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	UnifiedHrisBankinfoOutput *components.UnifiedHrisBankinfoOutput
}

func (o *RetrieveHrisBankInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveHrisBankInfoResponse) GetUnifiedHrisBankinfoOutput() *components.UnifiedHrisBankinfoOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedHrisBankinfoOutput
}
