// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type RetrieveAtsCandidateRequest struct {
	// The connection token
	XConnectionToken string `header:"style=simple,explode=false,name=x-connection-token"`
	// id of the candidate you want to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Set to true to include data from the original Ats software.
	RemoteData *bool `queryParam:"style=form,explode=true,name=remote_data"`
}

func (o *RetrieveAtsCandidateRequest) GetXConnectionToken() string {
	if o == nil {
		return ""
	}
	return o.XConnectionToken
}

func (o *RetrieveAtsCandidateRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveAtsCandidateRequest) GetRemoteData() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

type RetrieveAtsCandidateResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	UnifiedAtsCandidateOutput *components.UnifiedAtsCandidateOutput
}

func (o *RetrieveAtsCandidateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveAtsCandidateResponse) GetUnifiedAtsCandidateOutput() *components.UnifiedAtsCandidateOutput {
	if o == nil {
		return nil
	}
	return o.UnifiedAtsCandidateOutput
}
