// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/go-sdk/models/components"
)

type UpdatePullFrequencyResponseBody struct {
}

type UpdatePullFrequencyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *UpdatePullFrequencyResponseBody
}

func (o *UpdatePullFrequencyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePullFrequencyResponse) GetObject() *UpdatePullFrequencyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
