// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateBatchLinkedUserDto struct {
	LinkedUserOriginIds []string `json:"linked_user_origin_ids"`
	Alias               *string  `json:"alias"`
}

func (o *CreateBatchLinkedUserDto) GetLinkedUserOriginIds() []string {
	if o == nil {
		return nil
	}
	return o.LinkedUserOriginIds
}

func (o *CreateBatchLinkedUserDto) GetAlias() *string {
	if o == nil {
		return nil
	}
	return o.Alias
}
