// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EarningItem struct {
	// The amount of the earning
	Amount *float64 `json:"amount,omitempty"`
	// The type of the earning
	Type *string `json:"type,omitempty"`
}

func (o *EarningItem) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *EarningItem) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
