// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LoginDto struct {
	IDUser       *string `json:"id_user,omitempty"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
}

func (o *LoginDto) GetIDUser() *string {
	if o == nil {
		return nil
	}
	return o.IDUser
}

func (o *LoginDto) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *LoginDto) GetPasswordHash() string {
	if o == nil {
		return ""
	}
	return o.PasswordHash
}
