// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/panoratech/go-sdk/internal/utils"
)

type Method string

const (
	MethodGet    Method = "GET"
	MethodPost   Method = "POST"
	MethodPatch  Method = "PATCH"
	MethodDelete Method = "DELETE"
	MethodPut    Method = "PUT"
)

func (e Method) ToPointer() *Method {
	return &e
}
func (e *Method) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		fallthrough
	case "PATCH":
		fallthrough
	case "DELETE":
		fallthrough
	case "PUT":
		*e = Method(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Method: %v", v)
	}
}

type DataType string

const (
	DataTypeMapOfAny        DataType = "mapOfAny"
	DataTypeArrayOfMapOfAny DataType = "arrayOfMapOfAny"
)

type Data struct {
	MapOfAny        map[string]any
	ArrayOfMapOfAny []map[string]any

	Type DataType
}

func CreateDataMapOfAny(mapOfAny map[string]any) Data {
	typ := DataTypeMapOfAny

	return Data{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateDataArrayOfMapOfAny(arrayOfMapOfAny []map[string]any) Data {
	typ := DataTypeArrayOfMapOfAny

	return Data{
		ArrayOfMapOfAny: arrayOfMapOfAny,
		Type:            typ,
	}
}

func (u *Data) UnmarshalJSON(data []byte) error {

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, true); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = DataTypeMapOfAny
		return nil
	}

	var arrayOfMapOfAny []map[string]any = []map[string]any{}
	if err := utils.UnmarshalJSON(data, &arrayOfMapOfAny, "", true, true); err == nil {
		u.ArrayOfMapOfAny = arrayOfMapOfAny
		u.Type = DataTypeArrayOfMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Data", string(data))
}

func (u Data) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.ArrayOfMapOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfMapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Data: all fields are null")
}

type PassThroughRequestDto struct {
	Method  Method         `json:"method"`
	Path    *string        `json:"path"`
	Data    *Data          `json:"data,omitempty"`
	Headers map[string]any `json:"headers,omitempty"`
}

func (o *PassThroughRequestDto) GetMethod() Method {
	if o == nil {
		return Method("")
	}
	return o.Method
}

func (o *PassThroughRequestDto) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *PassThroughRequestDto) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PassThroughRequestDto) GetHeaders() map[string]any {
	if o == nil {
		return nil
	}
	return o.Headers
}
