// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PassThroughResponseData struct {
}

type PassThroughResponse struct {
	URL    string                  `json:"url"`
	Status float64                 `json:"status"`
	Data   PassThroughResponseData `json:"data"`
}

func (o *PassThroughResponse) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *PassThroughResponse) GetStatus() float64 {
	if o == nil {
		return 0.0
	}
	return o.Status
}

func (o *PassThroughResponse) GetData() PassThroughResponseData {
	if o == nil {
		return PassThroughResponseData{}
	}
	return o.Data
}
