// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type Vertical string

const (
	VerticalTicketing           Vertical = "ticketing"
	VerticalAccounting          Vertical = "accounting"
	VerticalCrm                 Vertical = "crm"
	VerticalFilestorage         Vertical = "filestorage"
	VerticalEcommerce           Vertical = "ecommerce"
	VerticalMarketingautomation Vertical = "marketingautomation"
)

func (e Vertical) ToPointer() *Vertical {
	return &e
}
func (e *Vertical) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ticketing":
		fallthrough
	case "accounting":
		fallthrough
	case "crm":
		fallthrough
	case "filestorage":
		fallthrough
	case "ecommerce":
		fallthrough
	case "marketingautomation":
		*e = Vertical(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Vertical: %v", v)
	}
}

type Status string

const (
	StatusSuccess Status = "success"
	StatusFail    Status = "fail"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "fail":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type ResyncStatusDto struct {
	Timestamp *time.Time `json:"timestamp"`
	Vertical  *Vertical  `json:"vertical"`
	Provider  *string    `json:"provider"`
	Status    *Status    `json:"status"`
}

func (r ResyncStatusDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResyncStatusDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ResyncStatusDto) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *ResyncStatusDto) GetVertical() *Vertical {
	if o == nil {
		return nil
	}
	return o.Vertical
}

func (o *ResyncStatusDto) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *ResyncStatusDto) GetStatus() *Status {
	if o == nil {
		return nil
	}
	return o.Status
}
