// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignatureVerificationDto struct {
	// The payload event of the webhook.
	Payload map[string]any `json:"payload"`
	// The signature of the webhook.
	Signature *string `json:"signature"`
	// The secret of the webhook.
	Secret *string `json:"secret"`
}

func (o *SignatureVerificationDto) GetPayload() map[string]any {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *SignatureVerificationDto) GetSignature() *string {
	if o == nil {
		return nil
	}
	return o.Signature
}

func (o *SignatureVerificationDto) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
