// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

// UnifiedHrisDependentOutputFieldMappings - The custom field mappings of the object between the remote 3rd party & Panora
type UnifiedHrisDependentOutputFieldMappings struct {
}

// UnifiedHrisDependentOutputRemoteData - The remote data of the dependent in the context of the 3rd Party
type UnifiedHrisDependentOutputRemoteData struct {
}

type UnifiedHrisDependentOutput struct {
	// The first name of the dependent
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the dependent
	LastName *string `json:"last_name,omitempty"`
	// The middle name of the dependent
	MiddleName *string `json:"middle_name,omitempty"`
	// The relationship of the dependent to the employee
	Relationship *string `json:"relationship,omitempty"`
	// The date of birth of the dependent
	DateOfBirth *time.Time `json:"date_of_birth,omitempty"`
	// The gender of the dependent
	Gender *string `json:"gender,omitempty"`
	// The phone number of the dependent
	PhoneNumber *string `json:"phone_number,omitempty"`
	// The UUID of the home location
	HomeLocation *string `json:"home_location,omitempty"`
	// Indicates if the dependent is a student
	IsStudent *bool `json:"is_student,omitempty"`
	// The Social Security Number of the dependent
	Ssn *string `json:"ssn,omitempty"`
	// The UUID of the associated employee
	EmployeeID *string `json:"employee_id,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings *UnifiedHrisDependentOutputFieldMappings `json:"field_mappings,omitempty"`
	// The UUID of the dependent record
	ID *string `json:"id,omitempty"`
	// The remote ID of the dependent in the context of the 3rd Party
	RemoteID *string `json:"remote_id,omitempty"`
	// The remote data of the dependent in the context of the 3rd Party
	RemoteData *UnifiedHrisDependentOutputRemoteData `json:"remote_data,omitempty"`
	// The date when the dependent was created in the 3rd party system
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The created date of the dependent record
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The last modified date of the dependent record
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// Indicates if the dependent was deleted in the remote system
	RemoteWasDeleted *bool `json:"remote_was_deleted,omitempty"`
}

func (u UnifiedHrisDependentOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedHrisDependentOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedHrisDependentOutput) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *UnifiedHrisDependentOutput) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *UnifiedHrisDependentOutput) GetMiddleName() *string {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *UnifiedHrisDependentOutput) GetRelationship() *string {
	if o == nil {
		return nil
	}
	return o.Relationship
}

func (o *UnifiedHrisDependentOutput) GetDateOfBirth() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateOfBirth
}

func (o *UnifiedHrisDependentOutput) GetGender() *string {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *UnifiedHrisDependentOutput) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *UnifiedHrisDependentOutput) GetHomeLocation() *string {
	if o == nil {
		return nil
	}
	return o.HomeLocation
}

func (o *UnifiedHrisDependentOutput) GetIsStudent() *bool {
	if o == nil {
		return nil
	}
	return o.IsStudent
}

func (o *UnifiedHrisDependentOutput) GetSsn() *string {
	if o == nil {
		return nil
	}
	return o.Ssn
}

func (o *UnifiedHrisDependentOutput) GetEmployeeID() *string {
	if o == nil {
		return nil
	}
	return o.EmployeeID
}

func (o *UnifiedHrisDependentOutput) GetFieldMappings() *UnifiedHrisDependentOutputFieldMappings {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *UnifiedHrisDependentOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedHrisDependentOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedHrisDependentOutput) GetRemoteData() *UnifiedHrisDependentOutputRemoteData {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *UnifiedHrisDependentOutput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedHrisDependentOutput) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UnifiedHrisDependentOutput) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *UnifiedHrisDependentOutput) GetRemoteWasDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteWasDeleted
}
