// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UnifiedEcommerceOrderInputItems - The items in the order
type UnifiedEcommerceOrderInputItems struct {
}

// UnifiedEcommerceOrderInputFieldMappings - The custom field mappings of the object between the remote 3rd party & Panora
type UnifiedEcommerceOrderInputFieldMappings struct {
}

type UnifiedEcommerceOrderInput struct {
	// The status of the order
	OrderStatus *string `json:"order_status,omitempty"`
	// The number of the order
	OrderNumber *string `json:"order_number,omitempty"`
	// The payment status of the order
	PaymentStatus *string `json:"payment_status,omitempty"`
	// The currency of the order. Authorized value must be of type CurrencyCode (ISO 4217)
	Currency *string `json:"currency,omitempty"`
	// The total price of the order
	TotalPrice *float64 `json:"total_price,omitempty"`
	// The total discount on the order
	TotalDiscount *float64 `json:"total_discount,omitempty"`
	// The total shipping cost of the order
	TotalShipping *float64 `json:"total_shipping,omitempty"`
	// The total tax on the order
	TotalTax *float64 `json:"total_tax,omitempty"`
	// The fulfillment status of the order
	FulfillmentStatus *string `json:"fulfillment_status,omitempty"`
	// The UUID of the customer associated with the order
	CustomerID *string `json:"customer_id,omitempty"`
	// The items in the order
	Items *UnifiedEcommerceOrderInputItems `json:"items,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings *UnifiedEcommerceOrderInputFieldMappings `json:"field_mappings,omitempty"`
}

func (o *UnifiedEcommerceOrderInput) GetOrderStatus() *string {
	if o == nil {
		return nil
	}
	return o.OrderStatus
}

func (o *UnifiedEcommerceOrderInput) GetOrderNumber() *string {
	if o == nil {
		return nil
	}
	return o.OrderNumber
}

func (o *UnifiedEcommerceOrderInput) GetPaymentStatus() *string {
	if o == nil {
		return nil
	}
	return o.PaymentStatus
}

func (o *UnifiedEcommerceOrderInput) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *UnifiedEcommerceOrderInput) GetTotalPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalPrice
}

func (o *UnifiedEcommerceOrderInput) GetTotalDiscount() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalDiscount
}

func (o *UnifiedEcommerceOrderInput) GetTotalShipping() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalShipping
}

func (o *UnifiedEcommerceOrderInput) GetTotalTax() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalTax
}

func (o *UnifiedEcommerceOrderInput) GetFulfillmentStatus() *string {
	if o == nil {
		return nil
	}
	return o.FulfillmentStatus
}

func (o *UnifiedEcommerceOrderInput) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *UnifiedEcommerceOrderInput) GetItems() *UnifiedEcommerceOrderInputItems {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *UnifiedEcommerceOrderInput) GetFieldMappings() *UnifiedEcommerceOrderInputFieldMappings {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}
