// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedCrmContactInputFieldMappings struct {
}

type UnifiedCrmContactInput struct {
	// The first name of the contact
	FirstName string `json:"first_name"`
	// The last name of the contact
	LastName string `json:"last_name"`
	// The email addresses of the contact
	EmailAddresses []Email `json:"email_addresses,omitempty"`
	// The phone numbers of the contact
	PhoneNumbers []Phone `json:"phone_numbers,omitempty"`
	// The addresses of the contact
	Addresses []Address `json:"addresses,omitempty"`
	// The UUID of the user who owns the contact
	UserID        *string                             `json:"user_id,omitempty"`
	FieldMappings UnifiedCrmContactInputFieldMappings `json:"field_mappings"`
}

func (o *UnifiedCrmContactInput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *UnifiedCrmContactInput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *UnifiedCrmContactInput) GetEmailAddresses() []Email {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *UnifiedCrmContactInput) GetPhoneNumbers() []Phone {
	if o == nil {
		return nil
	}
	return o.PhoneNumbers
}

func (o *UnifiedCrmContactInput) GetAddresses() []Address {
	if o == nil {
		return nil
	}
	return o.Addresses
}

func (o *UnifiedCrmContactInput) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *UnifiedCrmContactInput) GetFieldMappings() UnifiedCrmContactInputFieldMappings {
	if o == nil {
		return UnifiedCrmContactInputFieldMappings{}
	}
	return o.FieldMappings
}
