// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedTicketingAttachmentOutputFieldMappings struct {
}

type UnifiedTicketingAttachmentOutputRemoteData struct {
}

type UnifiedTicketingAttachmentOutputCreatedAt struct {
}

type UnifiedTicketingAttachmentOutputModifiedAt struct {
}

type UnifiedTicketingAttachmentOutput struct {
	// The file name of the attachment
	FileName string `json:"file_name"`
	// The file url of the attachment
	FileURL string `json:"file_url"`
	// The uploader's UUID of the attachment
	Uploader string `json:"uploader"`
	// The UUID of the ticket the attachment is tied to
	TicketID *string `json:"ticket_id,omitempty"`
	// The UUID of the comment the attachment is tied to
	CommentID     *string                                       `json:"comment_id,omitempty"`
	FieldMappings UnifiedTicketingAttachmentOutputFieldMappings `json:"field_mappings"`
	// The UUID of the attachment
	ID *string `json:"id,omitempty"`
	// The id of the attachment in the context of the 3rd Party
	RemoteID   *string                                    `json:"remote_id,omitempty"`
	RemoteData UnifiedTicketingAttachmentOutputRemoteData `json:"remote_data"`
	CreatedAt  UnifiedTicketingAttachmentOutputCreatedAt  `json:"created_at"`
	ModifiedAt UnifiedTicketingAttachmentOutputModifiedAt `json:"modified_at"`
}

func (o *UnifiedTicketingAttachmentOutput) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *UnifiedTicketingAttachmentOutput) GetFileURL() string {
	if o == nil {
		return ""
	}
	return o.FileURL
}

func (o *UnifiedTicketingAttachmentOutput) GetUploader() string {
	if o == nil {
		return ""
	}
	return o.Uploader
}

func (o *UnifiedTicketingAttachmentOutput) GetTicketID() *string {
	if o == nil {
		return nil
	}
	return o.TicketID
}

func (o *UnifiedTicketingAttachmentOutput) GetCommentID() *string {
	if o == nil {
		return nil
	}
	return o.CommentID
}

func (o *UnifiedTicketingAttachmentOutput) GetFieldMappings() UnifiedTicketingAttachmentOutputFieldMappings {
	if o == nil {
		return UnifiedTicketingAttachmentOutputFieldMappings{}
	}
	return o.FieldMappings
}

func (o *UnifiedTicketingAttachmentOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedTicketingAttachmentOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedTicketingAttachmentOutput) GetRemoteData() UnifiedTicketingAttachmentOutputRemoteData {
	if o == nil {
		return UnifiedTicketingAttachmentOutputRemoteData{}
	}
	return o.RemoteData
}

func (o *UnifiedTicketingAttachmentOutput) GetCreatedAt() UnifiedTicketingAttachmentOutputCreatedAt {
	if o == nil {
		return UnifiedTicketingAttachmentOutputCreatedAt{}
	}
	return o.CreatedAt
}

func (o *UnifiedTicketingAttachmentOutput) GetModifiedAt() UnifiedTicketingAttachmentOutputModifiedAt {
	if o == nil {
		return UnifiedTicketingAttachmentOutputModifiedAt{}
	}
	return o.ModifiedAt
}
