// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedCrmStageOutputFieldMappings struct {
}

type UnifiedCrmStageOutputRemoteData struct {
}

type UnifiedCrmStageOutputCreatedAt struct {
}

type UnifiedCrmStageOutputModifiedAt struct {
}

type UnifiedCrmStageOutput struct {
	// The name of the stage
	StageName     string                             `json:"stage_name"`
	FieldMappings UnifiedCrmStageOutputFieldMappings `json:"field_mappings"`
	// The UUID of the stage
	ID *string `json:"id,omitempty"`
	// The id of the stage in the context of the Crm 3rd Party
	RemoteID   *string                         `json:"remote_id,omitempty"`
	RemoteData UnifiedCrmStageOutputRemoteData `json:"remote_data"`
	CreatedAt  UnifiedCrmStageOutputCreatedAt  `json:"created_at"`
	ModifiedAt UnifiedCrmStageOutputModifiedAt `json:"modified_at"`
}

func (o *UnifiedCrmStageOutput) GetStageName() string {
	if o == nil {
		return ""
	}
	return o.StageName
}

func (o *UnifiedCrmStageOutput) GetFieldMappings() UnifiedCrmStageOutputFieldMappings {
	if o == nil {
		return UnifiedCrmStageOutputFieldMappings{}
	}
	return o.FieldMappings
}

func (o *UnifiedCrmStageOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedCrmStageOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedCrmStageOutput) GetRemoteData() UnifiedCrmStageOutputRemoteData {
	if o == nil {
		return UnifiedCrmStageOutputRemoteData{}
	}
	return o.RemoteData
}

func (o *UnifiedCrmStageOutput) GetCreatedAt() UnifiedCrmStageOutputCreatedAt {
	if o == nil {
		return UnifiedCrmStageOutputCreatedAt{}
	}
	return o.CreatedAt
}

func (o *UnifiedCrmStageOutput) GetModifiedAt() UnifiedCrmStageOutputModifiedAt {
	if o == nil {
		return UnifiedCrmStageOutputModifiedAt{}
	}
	return o.ModifiedAt
}
