// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

// UnifiedAtsOfferOutputCreatedAt - The created date of the object
type UnifiedAtsOfferOutputCreatedAt struct {
}

// UnifiedAtsOfferOutputModifiedAt - The modified date of the object
type UnifiedAtsOfferOutputModifiedAt struct {
}

type UnifiedAtsOfferOutput struct {
	// The UUID of the creator
	CreatedBy *string `json:"created_by,omitempty"`
	// The remote creation date of the offer
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The closing date of the offer
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// The sending date of the offer
	SentAt *time.Time `json:"sent_at,omitempty"`
	// The start date of the offer
	StartDate *time.Time `json:"start_date,omitempty"`
	// The status of the offer
	Status *string `json:"status,omitempty"`
	// The UUID of the application
	ApplicationID *string `json:"application_id,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
	// The UUID of the offer
	ID *string `json:"id,omitempty"`
	// The remote ID of the offer in the context of the 3rd Party
	RemoteID *string `json:"remote_id,omitempty"`
	// The remote data of the offer in the context of the 3rd Party
	RemoteData map[string]any `json:"remote_data,omitempty"`
	// The created date of the object
	CreatedAt *UnifiedAtsOfferOutputCreatedAt `json:"created_at,omitempty"`
	// The modified date of the object
	ModifiedAt *UnifiedAtsOfferOutputModifiedAt `json:"modified_at,omitempty"`
}

func (u UnifiedAtsOfferOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedAtsOfferOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedAtsOfferOutput) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *UnifiedAtsOfferOutput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedAtsOfferOutput) GetClosedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ClosedAt
}

func (o *UnifiedAtsOfferOutput) GetSentAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.SentAt
}

func (o *UnifiedAtsOfferOutput) GetStartDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *UnifiedAtsOfferOutput) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UnifiedAtsOfferOutput) GetApplicationID() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationID
}

func (o *UnifiedAtsOfferOutput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *UnifiedAtsOfferOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedAtsOfferOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedAtsOfferOutput) GetRemoteData() map[string]any {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *UnifiedAtsOfferOutput) GetCreatedAt() *UnifiedAtsOfferOutputCreatedAt {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UnifiedAtsOfferOutput) GetModifiedAt() *UnifiedAtsOfferOutputModifiedAt {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}
