// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type UnifiedAtsInterviewInput struct {
	// The status of the interview
	Status *string `json:"status,omitempty"`
	// The UUID of the application
	ApplicationID *string `json:"application_id,omitempty"`
	// The UUID of the job interview stage
	JobInterviewStageID *string `json:"job_interview_stage_id,omitempty"`
	// The UUID of the organizer
	OrganizedBy *string `json:"organized_by,omitempty"`
	// The UUIDs of the interviewers
	Interviewers []string `json:"interviewers,omitempty"`
	// The location of the interview
	Location *string `json:"location,omitempty"`
	// The start date and time of the interview
	StartAt *time.Time `json:"start_at,omitempty"`
	// The end date and time of the interview
	EndAt *time.Time `json:"end_at,omitempty"`
	// The remote creation date of the interview
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The remote modification date of the interview
	RemoteUpdatedAt *time.Time `json:"remote_updated_at,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
}

func (u UnifiedAtsInterviewInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedAtsInterviewInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedAtsInterviewInput) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UnifiedAtsInterviewInput) GetApplicationID() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationID
}

func (o *UnifiedAtsInterviewInput) GetJobInterviewStageID() *string {
	if o == nil {
		return nil
	}
	return o.JobInterviewStageID
}

func (o *UnifiedAtsInterviewInput) GetOrganizedBy() *string {
	if o == nil {
		return nil
	}
	return o.OrganizedBy
}

func (o *UnifiedAtsInterviewInput) GetInterviewers() []string {
	if o == nil {
		return nil
	}
	return o.Interviewers
}

func (o *UnifiedAtsInterviewInput) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *UnifiedAtsInterviewInput) GetStartAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartAt
}

func (o *UnifiedAtsInterviewInput) GetEndAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndAt
}

func (o *UnifiedAtsInterviewInput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedAtsInterviewInput) GetRemoteUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteUpdatedAt
}

func (o *UnifiedAtsInterviewInput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}
