// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// UnifiedCrmCompanyInputIndustry - The industry of the company. Authorized values can be found in the Industry enum.
type UnifiedCrmCompanyInputIndustry string

const (
	UnifiedCrmCompanyInputIndustryAccounting                        UnifiedCrmCompanyInputIndustry = "ACCOUNTING"
	UnifiedCrmCompanyInputIndustryAirlinesAviation                  UnifiedCrmCompanyInputIndustry = "AIRLINES_AVIATION"
	UnifiedCrmCompanyInputIndustryAlternativeDisputeResolution      UnifiedCrmCompanyInputIndustry = "ALTERNATIVE_DISPUTE_RESOLUTION"
	UnifiedCrmCompanyInputIndustryAlternativeMedicine               UnifiedCrmCompanyInputIndustry = "ALTERNATIVE_MEDICINE"
	UnifiedCrmCompanyInputIndustryAnimation                         UnifiedCrmCompanyInputIndustry = "ANIMATION"
	UnifiedCrmCompanyInputIndustryApparelFashion                    UnifiedCrmCompanyInputIndustry = "APPAREL_FASHION"
	UnifiedCrmCompanyInputIndustryArchitecturePlanning              UnifiedCrmCompanyInputIndustry = "ARCHITECTURE_PLANNING"
	UnifiedCrmCompanyInputIndustryArtsAndCrafts                     UnifiedCrmCompanyInputIndustry = "ARTS_AND_CRAFTS"
	UnifiedCrmCompanyInputIndustryAutomotive                        UnifiedCrmCompanyInputIndustry = "AUTOMOTIVE"
	UnifiedCrmCompanyInputIndustryAviationAerospace                 UnifiedCrmCompanyInputIndustry = "AVIATION_AEROSPACE"
	UnifiedCrmCompanyInputIndustryBanking                           UnifiedCrmCompanyInputIndustry = "BANKING"
	UnifiedCrmCompanyInputIndustryBiotechnology                     UnifiedCrmCompanyInputIndustry = "BIOTECHNOLOGY"
	UnifiedCrmCompanyInputIndustryBroadcastMedia                    UnifiedCrmCompanyInputIndustry = "BROADCAST_MEDIA"
	UnifiedCrmCompanyInputIndustryBuildingMaterials                 UnifiedCrmCompanyInputIndustry = "BUILDING_MATERIALS"
	UnifiedCrmCompanyInputIndustryBusinessSuppliesAndEquipment      UnifiedCrmCompanyInputIndustry = "BUSINESS_SUPPLIES_AND_EQUIPMENT"
	UnifiedCrmCompanyInputIndustryCapitalMarkets                    UnifiedCrmCompanyInputIndustry = "CAPITAL_MARKETS"
	UnifiedCrmCompanyInputIndustryChemicals                         UnifiedCrmCompanyInputIndustry = "CHEMICALS"
	UnifiedCrmCompanyInputIndustryCivicSocialOrganization           UnifiedCrmCompanyInputIndustry = "CIVIC_SOCIAL_ORGANIZATION"
	UnifiedCrmCompanyInputIndustryCivilEngineering                  UnifiedCrmCompanyInputIndustry = "CIVIL_ENGINEERING"
	UnifiedCrmCompanyInputIndustryCommercialRealEstate              UnifiedCrmCompanyInputIndustry = "COMMERCIAL_REAL_ESTATE"
	UnifiedCrmCompanyInputIndustryComputerNetworkSecurity           UnifiedCrmCompanyInputIndustry = "COMPUTER_NETWORK_SECURITY"
	UnifiedCrmCompanyInputIndustryComputerGames                     UnifiedCrmCompanyInputIndustry = "COMPUTER_GAMES"
	UnifiedCrmCompanyInputIndustryComputerHardware                  UnifiedCrmCompanyInputIndustry = "COMPUTER_HARDWARE"
	UnifiedCrmCompanyInputIndustryComputerNetworking                UnifiedCrmCompanyInputIndustry = "COMPUTER_NETWORKING"
	UnifiedCrmCompanyInputIndustryComputerSoftware                  UnifiedCrmCompanyInputIndustry = "COMPUTER_SOFTWARE"
	UnifiedCrmCompanyInputIndustryInternet                          UnifiedCrmCompanyInputIndustry = "INTERNET"
	UnifiedCrmCompanyInputIndustryConstruction                      UnifiedCrmCompanyInputIndustry = "CONSTRUCTION"
	UnifiedCrmCompanyInputIndustryConsumerElectronics               UnifiedCrmCompanyInputIndustry = "CONSUMER_ELECTRONICS"
	UnifiedCrmCompanyInputIndustryConsumerGoods                     UnifiedCrmCompanyInputIndustry = "CONSUMER_GOODS"
	UnifiedCrmCompanyInputIndustryConsumerServices                  UnifiedCrmCompanyInputIndustry = "CONSUMER_SERVICES"
	UnifiedCrmCompanyInputIndustryCosmetics                         UnifiedCrmCompanyInputIndustry = "COSMETICS"
	UnifiedCrmCompanyInputIndustryDairy                             UnifiedCrmCompanyInputIndustry = "DAIRY"
	UnifiedCrmCompanyInputIndustryDefenseSpace                      UnifiedCrmCompanyInputIndustry = "DEFENSE_SPACE"
	UnifiedCrmCompanyInputIndustryDesign                            UnifiedCrmCompanyInputIndustry = "DESIGN"
	UnifiedCrmCompanyInputIndustryEducationManagement               UnifiedCrmCompanyInputIndustry = "EDUCATION_MANAGEMENT"
	UnifiedCrmCompanyInputIndustryELearning                         UnifiedCrmCompanyInputIndustry = "E_LEARNING"
	UnifiedCrmCompanyInputIndustryElectricalElectronicManufacturing UnifiedCrmCompanyInputIndustry = "ELECTRICAL_ELECTRONIC_MANUFACTURING"
	UnifiedCrmCompanyInputIndustryEntertainment                     UnifiedCrmCompanyInputIndustry = "ENTERTAINMENT"
	UnifiedCrmCompanyInputIndustryEnvironmentalServices             UnifiedCrmCompanyInputIndustry = "ENVIRONMENTAL_SERVICES"
	UnifiedCrmCompanyInputIndustryEventsServices                    UnifiedCrmCompanyInputIndustry = "EVENTS_SERVICES"
	UnifiedCrmCompanyInputIndustryExecutiveOffice                   UnifiedCrmCompanyInputIndustry = "EXECUTIVE_OFFICE"
	UnifiedCrmCompanyInputIndustryFacilitiesServices                UnifiedCrmCompanyInputIndustry = "FACILITIES_SERVICES"
	UnifiedCrmCompanyInputIndustryFarming                           UnifiedCrmCompanyInputIndustry = "FARMING"
	UnifiedCrmCompanyInputIndustryFinancialServices                 UnifiedCrmCompanyInputIndustry = "FINANCIAL_SERVICES"
	UnifiedCrmCompanyInputIndustryFineArt                           UnifiedCrmCompanyInputIndustry = "FINE_ART"
	UnifiedCrmCompanyInputIndustryFishery                           UnifiedCrmCompanyInputIndustry = "FISHERY"
	UnifiedCrmCompanyInputIndustryFoodBeverages                     UnifiedCrmCompanyInputIndustry = "FOOD_BEVERAGES"
	UnifiedCrmCompanyInputIndustryFoodProduction                    UnifiedCrmCompanyInputIndustry = "FOOD_PRODUCTION"
	UnifiedCrmCompanyInputIndustryFundRaising                       UnifiedCrmCompanyInputIndustry = "FUND_RAISING"
	UnifiedCrmCompanyInputIndustryFurniture                         UnifiedCrmCompanyInputIndustry = "FURNITURE"
	UnifiedCrmCompanyInputIndustryGamblingCasinos                   UnifiedCrmCompanyInputIndustry = "GAMBLING_CASINOS"
	UnifiedCrmCompanyInputIndustryGlassCeramicsConcrete             UnifiedCrmCompanyInputIndustry = "GLASS_CERAMICS_CONCRETE"
	UnifiedCrmCompanyInputIndustryGovernmentAdministration          UnifiedCrmCompanyInputIndustry = "GOVERNMENT_ADMINISTRATION"
	UnifiedCrmCompanyInputIndustryGovernmentRelations               UnifiedCrmCompanyInputIndustry = "GOVERNMENT_RELATIONS"
	UnifiedCrmCompanyInputIndustryGraphicDesign                     UnifiedCrmCompanyInputIndustry = "GRAPHIC_DESIGN"
	UnifiedCrmCompanyInputIndustryHealthWellnessAndFitness          UnifiedCrmCompanyInputIndustry = "HEALTH_WELLNESS_AND_FITNESS"
	UnifiedCrmCompanyInputIndustryHigherEducation                   UnifiedCrmCompanyInputIndustry = "HIGHER_EDUCATION"
	UnifiedCrmCompanyInputIndustryHospitalHealthCare                UnifiedCrmCompanyInputIndustry = "HOSPITAL_HEALTH_CARE"
	UnifiedCrmCompanyInputIndustryHospitality                       UnifiedCrmCompanyInputIndustry = "HOSPITALITY"
	UnifiedCrmCompanyInputIndustryHumanResources                    UnifiedCrmCompanyInputIndustry = "HUMAN_RESOURCES"
	UnifiedCrmCompanyInputIndustryImportAndExport                   UnifiedCrmCompanyInputIndustry = "IMPORT_AND_EXPORT"
	UnifiedCrmCompanyInputIndustryIndividualFamilyServices          UnifiedCrmCompanyInputIndustry = "INDIVIDUAL_FAMILY_SERVICES"
	UnifiedCrmCompanyInputIndustryIndustrialAutomation              UnifiedCrmCompanyInputIndustry = "INDUSTRIAL_AUTOMATION"
	UnifiedCrmCompanyInputIndustryInformationServices               UnifiedCrmCompanyInputIndustry = "INFORMATION_SERVICES"
	UnifiedCrmCompanyInputIndustryInformationTechnologyAndServices  UnifiedCrmCompanyInputIndustry = "INFORMATION_TECHNOLOGY_AND_SERVICES"
	UnifiedCrmCompanyInputIndustryInsurance                         UnifiedCrmCompanyInputIndustry = "INSURANCE"
	UnifiedCrmCompanyInputIndustryInternationalAffairs              UnifiedCrmCompanyInputIndustry = "INTERNATIONAL_AFFAIRS"
	UnifiedCrmCompanyInputIndustryInternationalTradeAndDevelopment  UnifiedCrmCompanyInputIndustry = "INTERNATIONAL_TRADE_AND_DEVELOPMENT"
	UnifiedCrmCompanyInputIndustryInvestmentBanking                 UnifiedCrmCompanyInputIndustry = "INVESTMENT_BANKING"
	UnifiedCrmCompanyInputIndustryInvestmentManagement              UnifiedCrmCompanyInputIndustry = "INVESTMENT_MANAGEMENT"
	UnifiedCrmCompanyInputIndustryJudiciary                         UnifiedCrmCompanyInputIndustry = "JUDICIARY"
	UnifiedCrmCompanyInputIndustryLawEnforcement                    UnifiedCrmCompanyInputIndustry = "LAW_ENFORCEMENT"
	UnifiedCrmCompanyInputIndustryLawPractice                       UnifiedCrmCompanyInputIndustry = "LAW_PRACTICE"
	UnifiedCrmCompanyInputIndustryLegalServices                     UnifiedCrmCompanyInputIndustry = "LEGAL_SERVICES"
	UnifiedCrmCompanyInputIndustryLegislativeOffice                 UnifiedCrmCompanyInputIndustry = "LEGISLATIVE_OFFICE"
	UnifiedCrmCompanyInputIndustryLeisureTravelTourism              UnifiedCrmCompanyInputIndustry = "LEISURE_TRAVEL_TOURISM"
	UnifiedCrmCompanyInputIndustryLibraries                         UnifiedCrmCompanyInputIndustry = "LIBRARIES"
	UnifiedCrmCompanyInputIndustryLogisticsAndSupplyChain           UnifiedCrmCompanyInputIndustry = "LOGISTICS_AND_SUPPLY_CHAIN"
	UnifiedCrmCompanyInputIndustryLuxuryGoodsJewelry                UnifiedCrmCompanyInputIndustry = "LUXURY_GOODS_JEWELRY"
	UnifiedCrmCompanyInputIndustryMachinery                         UnifiedCrmCompanyInputIndustry = "MACHINERY"
	UnifiedCrmCompanyInputIndustryManagementConsulting              UnifiedCrmCompanyInputIndustry = "MANAGEMENT_CONSULTING"
	UnifiedCrmCompanyInputIndustryMaritime                          UnifiedCrmCompanyInputIndustry = "MARITIME"
	UnifiedCrmCompanyInputIndustryMarketResearch                    UnifiedCrmCompanyInputIndustry = "MARKET_RESEARCH"
	UnifiedCrmCompanyInputIndustryMarketingAndAdvertising           UnifiedCrmCompanyInputIndustry = "MARKETING_AND_ADVERTISING"
	UnifiedCrmCompanyInputIndustryMechanicalOrIndustrialEngineering UnifiedCrmCompanyInputIndustry = "MECHANICAL_OR_INDUSTRIAL_ENGINEERING"
	UnifiedCrmCompanyInputIndustryMediaProduction                   UnifiedCrmCompanyInputIndustry = "MEDIA_PRODUCTION"
	UnifiedCrmCompanyInputIndustryMedicalDevices                    UnifiedCrmCompanyInputIndustry = "MEDICAL_DEVICES"
	UnifiedCrmCompanyInputIndustryMedicalPractice                   UnifiedCrmCompanyInputIndustry = "MEDICAL_PRACTICE"
	UnifiedCrmCompanyInputIndustryMentalHealthCare                  UnifiedCrmCompanyInputIndustry = "MENTAL_HEALTH_CARE"
	UnifiedCrmCompanyInputIndustryMilitary                          UnifiedCrmCompanyInputIndustry = "MILITARY"
	UnifiedCrmCompanyInputIndustryMiningMetals                      UnifiedCrmCompanyInputIndustry = "MINING_METALS"
	UnifiedCrmCompanyInputIndustryMotionPicturesAndFilm             UnifiedCrmCompanyInputIndustry = "MOTION_PICTURES_AND_FILM"
	UnifiedCrmCompanyInputIndustryMuseumsAndInstitutions            UnifiedCrmCompanyInputIndustry = "MUSEUMS_AND_INSTITUTIONS"
	UnifiedCrmCompanyInputIndustryMusic                             UnifiedCrmCompanyInputIndustry = "MUSIC"
	UnifiedCrmCompanyInputIndustryNanotechnology                    UnifiedCrmCompanyInputIndustry = "NANOTECHNOLOGY"
	UnifiedCrmCompanyInputIndustryNewspapers                        UnifiedCrmCompanyInputIndustry = "NEWSPAPERS"
	UnifiedCrmCompanyInputIndustryNonProfitOrganizationManagement   UnifiedCrmCompanyInputIndustry = "NON_PROFIT_ORGANIZATION_MANAGEMENT"
	UnifiedCrmCompanyInputIndustryOilEnergy                         UnifiedCrmCompanyInputIndustry = "OIL_ENERGY"
	UnifiedCrmCompanyInputIndustryOnlineMedia                       UnifiedCrmCompanyInputIndustry = "ONLINE_MEDIA"
	UnifiedCrmCompanyInputIndustryOutsourcingOffshoring             UnifiedCrmCompanyInputIndustry = "OUTSOURCING_OFFSHORING"
	UnifiedCrmCompanyInputIndustryPackageFreightDelivery            UnifiedCrmCompanyInputIndustry = "PACKAGE_FREIGHT_DELIVERY"
	UnifiedCrmCompanyInputIndustryPackagingAndContainers            UnifiedCrmCompanyInputIndustry = "PACKAGING_AND_CONTAINERS"
	UnifiedCrmCompanyInputIndustryPaperForestProducts               UnifiedCrmCompanyInputIndustry = "PAPER_FOREST_PRODUCTS"
	UnifiedCrmCompanyInputIndustryPerformingArts                    UnifiedCrmCompanyInputIndustry = "PERFORMING_ARTS"
	UnifiedCrmCompanyInputIndustryPharmaceuticals                   UnifiedCrmCompanyInputIndustry = "PHARMACEUTICALS"
	UnifiedCrmCompanyInputIndustryPhilanthropy                      UnifiedCrmCompanyInputIndustry = "PHILANTHROPY"
	UnifiedCrmCompanyInputIndustryPhotography                       UnifiedCrmCompanyInputIndustry = "PHOTOGRAPHY"
	UnifiedCrmCompanyInputIndustryPlastics                          UnifiedCrmCompanyInputIndustry = "PLASTICS"
	UnifiedCrmCompanyInputIndustryPoliticalOrganization             UnifiedCrmCompanyInputIndustry = "POLITICAL_ORGANIZATION"
	UnifiedCrmCompanyInputIndustryPrimarySecondaryEducation         UnifiedCrmCompanyInputIndustry = "PRIMARY_SECONDARY_EDUCATION"
	UnifiedCrmCompanyInputIndustryPrinting                          UnifiedCrmCompanyInputIndustry = "PRINTING"
	UnifiedCrmCompanyInputIndustryProfessionalTrainingCoaching      UnifiedCrmCompanyInputIndustry = "PROFESSIONAL_TRAINING_COACHING"
	UnifiedCrmCompanyInputIndustryProgramDevelopment                UnifiedCrmCompanyInputIndustry = "PROGRAM_DEVELOPMENT"
	UnifiedCrmCompanyInputIndustryPublicPolicy                      UnifiedCrmCompanyInputIndustry = "PUBLIC_POLICY"
	UnifiedCrmCompanyInputIndustryPublicRelationsAndCommunications  UnifiedCrmCompanyInputIndustry = "PUBLIC_RELATIONS_AND_COMMUNICATIONS"
	UnifiedCrmCompanyInputIndustryPublicSafety                      UnifiedCrmCompanyInputIndustry = "PUBLIC_SAFETY"
	UnifiedCrmCompanyInputIndustryPublishing                        UnifiedCrmCompanyInputIndustry = "PUBLISHING"
	UnifiedCrmCompanyInputIndustryRailroadManufacture               UnifiedCrmCompanyInputIndustry = "RAILROAD_MANUFACTURE"
	UnifiedCrmCompanyInputIndustryRanching                          UnifiedCrmCompanyInputIndustry = "RANCHING"
	UnifiedCrmCompanyInputIndustryRealEstate                        UnifiedCrmCompanyInputIndustry = "REAL_ESTATE"
	UnifiedCrmCompanyInputIndustryRecreationalFacilitiesAndServices UnifiedCrmCompanyInputIndustry = "RECREATIONAL_FACILITIES_AND_SERVICES"
	UnifiedCrmCompanyInputIndustryReligiousInstitutions             UnifiedCrmCompanyInputIndustry = "RELIGIOUS_INSTITUTIONS"
	UnifiedCrmCompanyInputIndustryRenewablesEnvironment             UnifiedCrmCompanyInputIndustry = "RENEWABLES_ENVIRONMENT"
	UnifiedCrmCompanyInputIndustryResearch                          UnifiedCrmCompanyInputIndustry = "RESEARCH"
	UnifiedCrmCompanyInputIndustryRestaurants                       UnifiedCrmCompanyInputIndustry = "RESTAURANTS"
	UnifiedCrmCompanyInputIndustryRetail                            UnifiedCrmCompanyInputIndustry = "RETAIL"
	UnifiedCrmCompanyInputIndustrySecurityAndInvestigations         UnifiedCrmCompanyInputIndustry = "SECURITY_AND_INVESTIGATIONS"
	UnifiedCrmCompanyInputIndustrySemiconductors                    UnifiedCrmCompanyInputIndustry = "SEMICONDUCTORS"
	UnifiedCrmCompanyInputIndustryShipbuilding                      UnifiedCrmCompanyInputIndustry = "SHIPBUILDING"
	UnifiedCrmCompanyInputIndustrySportingGoods                     UnifiedCrmCompanyInputIndustry = "SPORTING_GOODS"
	UnifiedCrmCompanyInputIndustrySports                            UnifiedCrmCompanyInputIndustry = "SPORTS"
	UnifiedCrmCompanyInputIndustryStaffingAndRecruiting             UnifiedCrmCompanyInputIndustry = "STAFFING_AND_RECRUITING"
	UnifiedCrmCompanyInputIndustrySupermarkets                      UnifiedCrmCompanyInputIndustry = "SUPERMARKETS"
	UnifiedCrmCompanyInputIndustryTelecommunications                UnifiedCrmCompanyInputIndustry = "TELECOMMUNICATIONS"
	UnifiedCrmCompanyInputIndustryTextiles                          UnifiedCrmCompanyInputIndustry = "TEXTILES"
	UnifiedCrmCompanyInputIndustryThinkTanks                        UnifiedCrmCompanyInputIndustry = "THINK_TANKS"
	UnifiedCrmCompanyInputIndustryTobacco                           UnifiedCrmCompanyInputIndustry = "TOBACCO"
	UnifiedCrmCompanyInputIndustryTranslationAndLocalization        UnifiedCrmCompanyInputIndustry = "TRANSLATION_AND_LOCALIZATION"
	UnifiedCrmCompanyInputIndustryTransportationTruckingRailroad    UnifiedCrmCompanyInputIndustry = "TRANSPORTATION_TRUCKING_RAILROAD"
	UnifiedCrmCompanyInputIndustryUtilities                         UnifiedCrmCompanyInputIndustry = "UTILITIES"
	UnifiedCrmCompanyInputIndustryVentureCapitalPrivateEquity       UnifiedCrmCompanyInputIndustry = "VENTURE_CAPITAL_PRIVATE_EQUITY"
	UnifiedCrmCompanyInputIndustryVeterinary                        UnifiedCrmCompanyInputIndustry = "VETERINARY"
	UnifiedCrmCompanyInputIndustryWarehousing                       UnifiedCrmCompanyInputIndustry = "WAREHOUSING"
	UnifiedCrmCompanyInputIndustryWholesale                         UnifiedCrmCompanyInputIndustry = "WHOLESALE"
	UnifiedCrmCompanyInputIndustryWineAndSpirits                    UnifiedCrmCompanyInputIndustry = "WINE_AND_SPIRITS"
	UnifiedCrmCompanyInputIndustryWireless                          UnifiedCrmCompanyInputIndustry = "WIRELESS"
	UnifiedCrmCompanyInputIndustryWritingAndEditing                 UnifiedCrmCompanyInputIndustry = "WRITING_AND_EDITING"
)

func (e UnifiedCrmCompanyInputIndustry) ToPointer() *UnifiedCrmCompanyInputIndustry {
	return &e
}
func (e *UnifiedCrmCompanyInputIndustry) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNTING":
		fallthrough
	case "AIRLINES_AVIATION":
		fallthrough
	case "ALTERNATIVE_DISPUTE_RESOLUTION":
		fallthrough
	case "ALTERNATIVE_MEDICINE":
		fallthrough
	case "ANIMATION":
		fallthrough
	case "APPAREL_FASHION":
		fallthrough
	case "ARCHITECTURE_PLANNING":
		fallthrough
	case "ARTS_AND_CRAFTS":
		fallthrough
	case "AUTOMOTIVE":
		fallthrough
	case "AVIATION_AEROSPACE":
		fallthrough
	case "BANKING":
		fallthrough
	case "BIOTECHNOLOGY":
		fallthrough
	case "BROADCAST_MEDIA":
		fallthrough
	case "BUILDING_MATERIALS":
		fallthrough
	case "BUSINESS_SUPPLIES_AND_EQUIPMENT":
		fallthrough
	case "CAPITAL_MARKETS":
		fallthrough
	case "CHEMICALS":
		fallthrough
	case "CIVIC_SOCIAL_ORGANIZATION":
		fallthrough
	case "CIVIL_ENGINEERING":
		fallthrough
	case "COMMERCIAL_REAL_ESTATE":
		fallthrough
	case "COMPUTER_NETWORK_SECURITY":
		fallthrough
	case "COMPUTER_GAMES":
		fallthrough
	case "COMPUTER_HARDWARE":
		fallthrough
	case "COMPUTER_NETWORKING":
		fallthrough
	case "COMPUTER_SOFTWARE":
		fallthrough
	case "INTERNET":
		fallthrough
	case "CONSTRUCTION":
		fallthrough
	case "CONSUMER_ELECTRONICS":
		fallthrough
	case "CONSUMER_GOODS":
		fallthrough
	case "CONSUMER_SERVICES":
		fallthrough
	case "COSMETICS":
		fallthrough
	case "DAIRY":
		fallthrough
	case "DEFENSE_SPACE":
		fallthrough
	case "DESIGN":
		fallthrough
	case "EDUCATION_MANAGEMENT":
		fallthrough
	case "E_LEARNING":
		fallthrough
	case "ELECTRICAL_ELECTRONIC_MANUFACTURING":
		fallthrough
	case "ENTERTAINMENT":
		fallthrough
	case "ENVIRONMENTAL_SERVICES":
		fallthrough
	case "EVENTS_SERVICES":
		fallthrough
	case "EXECUTIVE_OFFICE":
		fallthrough
	case "FACILITIES_SERVICES":
		fallthrough
	case "FARMING":
		fallthrough
	case "FINANCIAL_SERVICES":
		fallthrough
	case "FINE_ART":
		fallthrough
	case "FISHERY":
		fallthrough
	case "FOOD_BEVERAGES":
		fallthrough
	case "FOOD_PRODUCTION":
		fallthrough
	case "FUND_RAISING":
		fallthrough
	case "FURNITURE":
		fallthrough
	case "GAMBLING_CASINOS":
		fallthrough
	case "GLASS_CERAMICS_CONCRETE":
		fallthrough
	case "GOVERNMENT_ADMINISTRATION":
		fallthrough
	case "GOVERNMENT_RELATIONS":
		fallthrough
	case "GRAPHIC_DESIGN":
		fallthrough
	case "HEALTH_WELLNESS_AND_FITNESS":
		fallthrough
	case "HIGHER_EDUCATION":
		fallthrough
	case "HOSPITAL_HEALTH_CARE":
		fallthrough
	case "HOSPITALITY":
		fallthrough
	case "HUMAN_RESOURCES":
		fallthrough
	case "IMPORT_AND_EXPORT":
		fallthrough
	case "INDIVIDUAL_FAMILY_SERVICES":
		fallthrough
	case "INDUSTRIAL_AUTOMATION":
		fallthrough
	case "INFORMATION_SERVICES":
		fallthrough
	case "INFORMATION_TECHNOLOGY_AND_SERVICES":
		fallthrough
	case "INSURANCE":
		fallthrough
	case "INTERNATIONAL_AFFAIRS":
		fallthrough
	case "INTERNATIONAL_TRADE_AND_DEVELOPMENT":
		fallthrough
	case "INVESTMENT_BANKING":
		fallthrough
	case "INVESTMENT_MANAGEMENT":
		fallthrough
	case "JUDICIARY":
		fallthrough
	case "LAW_ENFORCEMENT":
		fallthrough
	case "LAW_PRACTICE":
		fallthrough
	case "LEGAL_SERVICES":
		fallthrough
	case "LEGISLATIVE_OFFICE":
		fallthrough
	case "LEISURE_TRAVEL_TOURISM":
		fallthrough
	case "LIBRARIES":
		fallthrough
	case "LOGISTICS_AND_SUPPLY_CHAIN":
		fallthrough
	case "LUXURY_GOODS_JEWELRY":
		fallthrough
	case "MACHINERY":
		fallthrough
	case "MANAGEMENT_CONSULTING":
		fallthrough
	case "MARITIME":
		fallthrough
	case "MARKET_RESEARCH":
		fallthrough
	case "MARKETING_AND_ADVERTISING":
		fallthrough
	case "MECHANICAL_OR_INDUSTRIAL_ENGINEERING":
		fallthrough
	case "MEDIA_PRODUCTION":
		fallthrough
	case "MEDICAL_DEVICES":
		fallthrough
	case "MEDICAL_PRACTICE":
		fallthrough
	case "MENTAL_HEALTH_CARE":
		fallthrough
	case "MILITARY":
		fallthrough
	case "MINING_METALS":
		fallthrough
	case "MOTION_PICTURES_AND_FILM":
		fallthrough
	case "MUSEUMS_AND_INSTITUTIONS":
		fallthrough
	case "MUSIC":
		fallthrough
	case "NANOTECHNOLOGY":
		fallthrough
	case "NEWSPAPERS":
		fallthrough
	case "NON_PROFIT_ORGANIZATION_MANAGEMENT":
		fallthrough
	case "OIL_ENERGY":
		fallthrough
	case "ONLINE_MEDIA":
		fallthrough
	case "OUTSOURCING_OFFSHORING":
		fallthrough
	case "PACKAGE_FREIGHT_DELIVERY":
		fallthrough
	case "PACKAGING_AND_CONTAINERS":
		fallthrough
	case "PAPER_FOREST_PRODUCTS":
		fallthrough
	case "PERFORMING_ARTS":
		fallthrough
	case "PHARMACEUTICALS":
		fallthrough
	case "PHILANTHROPY":
		fallthrough
	case "PHOTOGRAPHY":
		fallthrough
	case "PLASTICS":
		fallthrough
	case "POLITICAL_ORGANIZATION":
		fallthrough
	case "PRIMARY_SECONDARY_EDUCATION":
		fallthrough
	case "PRINTING":
		fallthrough
	case "PROFESSIONAL_TRAINING_COACHING":
		fallthrough
	case "PROGRAM_DEVELOPMENT":
		fallthrough
	case "PUBLIC_POLICY":
		fallthrough
	case "PUBLIC_RELATIONS_AND_COMMUNICATIONS":
		fallthrough
	case "PUBLIC_SAFETY":
		fallthrough
	case "PUBLISHING":
		fallthrough
	case "RAILROAD_MANUFACTURE":
		fallthrough
	case "RANCHING":
		fallthrough
	case "REAL_ESTATE":
		fallthrough
	case "RECREATIONAL_FACILITIES_AND_SERVICES":
		fallthrough
	case "RELIGIOUS_INSTITUTIONS":
		fallthrough
	case "RENEWABLES_ENVIRONMENT":
		fallthrough
	case "RESEARCH":
		fallthrough
	case "RESTAURANTS":
		fallthrough
	case "RETAIL":
		fallthrough
	case "SECURITY_AND_INVESTIGATIONS":
		fallthrough
	case "SEMICONDUCTORS":
		fallthrough
	case "SHIPBUILDING":
		fallthrough
	case "SPORTING_GOODS":
		fallthrough
	case "SPORTS":
		fallthrough
	case "STAFFING_AND_RECRUITING":
		fallthrough
	case "SUPERMARKETS":
		fallthrough
	case "TELECOMMUNICATIONS":
		fallthrough
	case "TEXTILES":
		fallthrough
	case "THINK_TANKS":
		fallthrough
	case "TOBACCO":
		fallthrough
	case "TRANSLATION_AND_LOCALIZATION":
		fallthrough
	case "TRANSPORTATION_TRUCKING_RAILROAD":
		fallthrough
	case "UTILITIES":
		fallthrough
	case "VENTURE_CAPITAL_PRIVATE_EQUITY":
		fallthrough
	case "VETERINARY":
		fallthrough
	case "WAREHOUSING":
		fallthrough
	case "WHOLESALE":
		fallthrough
	case "WINE_AND_SPIRITS":
		fallthrough
	case "WIRELESS":
		fallthrough
	case "WRITING_AND_EDITING":
		*e = UnifiedCrmCompanyInputIndustry(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnifiedCrmCompanyInputIndustry: %v", v)
	}
}

type UnifiedCrmCompanyInput struct {
	// The name of the company
	Name *string `json:"name"`
	// The industry of the company. Authorized values can be found in the Industry enum.
	Industry *UnifiedCrmCompanyInputIndustry `json:"industry,omitempty"`
	// The number of employees of the company
	NumberOfEmployees *float64 `json:"number_of_employees,omitempty"`
	// The UUID of the user who owns the company
	UserID *string `json:"user_id,omitempty"`
	// The email addresses of the company
	EmailAddresses []Email `json:"email_addresses,omitempty"`
	// The addresses of the company
	Addresses []Address `json:"addresses,omitempty"`
	// The phone numbers of the company
	PhoneNumbers []Phone `json:"phone_numbers,omitempty"`
	// The custom field mappings of the company between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
}

func (o *UnifiedCrmCompanyInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnifiedCrmCompanyInput) GetIndustry() *UnifiedCrmCompanyInputIndustry {
	if o == nil {
		return nil
	}
	return o.Industry
}

func (o *UnifiedCrmCompanyInput) GetNumberOfEmployees() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberOfEmployees
}

func (o *UnifiedCrmCompanyInput) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *UnifiedCrmCompanyInput) GetEmailAddresses() []Email {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *UnifiedCrmCompanyInput) GetAddresses() []Address {
	if o == nil {
		return nil
	}
	return o.Addresses
}

func (o *UnifiedCrmCompanyInput) GetPhoneNumbers() []Phone {
	if o == nil {
		return nil
	}
	return o.PhoneNumbers
}

func (o *UnifiedCrmCompanyInput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}
