// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type UnifiedAtsCandidateInputFieldMappings struct {
}

type UnifiedAtsCandidateInput struct {
	// The first name of the candidate
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the candidate
	LastName *string `json:"last_name,omitempty"`
	// The company of the candidate
	Company *string `json:"company,omitempty"`
	// The title of the candidate
	Title *string `json:"title,omitempty"`
	// The locations of the candidate
	Locations *string `json:"locations,omitempty"`
	// Whether the candidate is private
	IsPrivate *bool `json:"is_private,omitempty"`
	// Whether the candidate is reachable by email
	EmailReachable *bool `json:"email_reachable,omitempty"`
	// The remote creation date of the candidate
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The remote modification date of the candidate
	RemoteModifiedAt *time.Time `json:"remote_modified_at,omitempty"`
	// The last interaction date with the candidate
	LastInteractionAt *time.Time `json:"last_interaction_at,omitempty"`
	// The attachments UUIDs of the candidate
	Attachments []string `json:"attachments,omitempty"`
	// The applications UUIDs of the candidate
	Applications []string `json:"applications,omitempty"`
	// The tags of the candidate
	Tags []string `json:"tags,omitempty"`
	// The urls of the candidate, possible values for Url type are WEBSITE, BLOG, LINKEDIN, GITHUB, or OTHER
	Urls []URL `json:"urls,omitempty"`
	// The phone numbers of the candidate
	PhoneNumbers []Phone `json:"phone_numbers,omitempty"`
	// The email addresses of the candidate
	EmailAddresses []Email                               `json:"email_addresses,omitempty"`
	FieldMappings  UnifiedAtsCandidateInputFieldMappings `json:"field_mappings"`
}

func (u UnifiedAtsCandidateInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedAtsCandidateInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedAtsCandidateInput) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *UnifiedAtsCandidateInput) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *UnifiedAtsCandidateInput) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *UnifiedAtsCandidateInput) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UnifiedAtsCandidateInput) GetLocations() *string {
	if o == nil {
		return nil
	}
	return o.Locations
}

func (o *UnifiedAtsCandidateInput) GetIsPrivate() *bool {
	if o == nil {
		return nil
	}
	return o.IsPrivate
}

func (o *UnifiedAtsCandidateInput) GetEmailReachable() *bool {
	if o == nil {
		return nil
	}
	return o.EmailReachable
}

func (o *UnifiedAtsCandidateInput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedAtsCandidateInput) GetRemoteModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteModifiedAt
}

func (o *UnifiedAtsCandidateInput) GetLastInteractionAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastInteractionAt
}

func (o *UnifiedAtsCandidateInput) GetAttachments() []string {
	if o == nil {
		return nil
	}
	return o.Attachments
}

func (o *UnifiedAtsCandidateInput) GetApplications() []string {
	if o == nil {
		return nil
	}
	return o.Applications
}

func (o *UnifiedAtsCandidateInput) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *UnifiedAtsCandidateInput) GetUrls() []URL {
	if o == nil {
		return nil
	}
	return o.Urls
}

func (o *UnifiedAtsCandidateInput) GetPhoneNumbers() []Phone {
	if o == nil {
		return nil
	}
	return o.PhoneNumbers
}

func (o *UnifiedAtsCandidateInput) GetEmailAddresses() []Email {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *UnifiedAtsCandidateInput) GetFieldMappings() UnifiedAtsCandidateInputFieldMappings {
	if o == nil {
		return UnifiedAtsCandidateInputFieldMappings{}
	}
	return o.FieldMappings
}
