// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedCrmNoteInputFieldMappings struct {
}

type UnifiedCrmNoteInput struct {
	// The content of the note
	Content string `json:"content"`
	// The UUID of the user tied the note
	UserID *string `json:"user_id,omitempty"`
	// The UUID of the company tied to the note
	CompanyID *string `json:"company_id,omitempty"`
	// The UUID fo the contact tied to the note
	ContactID *string `json:"contact_id,omitempty"`
	// The UUID of the deal tied to the note
	DealID        *string                          `json:"deal_id,omitempty"`
	FieldMappings UnifiedCrmNoteInputFieldMappings `json:"field_mappings"`
}

func (o *UnifiedCrmNoteInput) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *UnifiedCrmNoteInput) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *UnifiedCrmNoteInput) GetCompanyID() *string {
	if o == nil {
		return nil
	}
	return o.CompanyID
}

func (o *UnifiedCrmNoteInput) GetContactID() *string {
	if o == nil {
		return nil
	}
	return o.ContactID
}

func (o *UnifiedCrmNoteInput) GetDealID() *string {
	if o == nil {
		return nil
	}
	return o.DealID
}

func (o *UnifiedCrmNoteInput) GetFieldMappings() UnifiedCrmNoteInputFieldMappings {
	if o == nil {
		return UnifiedCrmNoteInputFieldMappings{}
	}
	return o.FieldMappings
}
