// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedFilestorageFileInputFieldMappings struct {
}

type UnifiedFilestorageFileInput struct {
	// The name of the file
	Name string `json:"name"`
	// The url of the file
	FileURL string `json:"file_url"`
	// The mime type of the file
	MimeType string `json:"mime_type"`
	// The size of the file
	Size string `json:"size"`
	// The UUID of the folder tied to the file
	FolderID string `json:"folder_id"`
	// The UUID of the permission tied to the file
	Permission string `json:"permission"`
	// The UUID of the shared link tied to the file
	SharedLink    string                                   `json:"shared_link"`
	FieldMappings UnifiedFilestorageFileInputFieldMappings `json:"field_mappings"`
}

func (o *UnifiedFilestorageFileInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UnifiedFilestorageFileInput) GetFileURL() string {
	if o == nil {
		return ""
	}
	return o.FileURL
}

func (o *UnifiedFilestorageFileInput) GetMimeType() string {
	if o == nil {
		return ""
	}
	return o.MimeType
}

func (o *UnifiedFilestorageFileInput) GetSize() string {
	if o == nil {
		return ""
	}
	return o.Size
}

func (o *UnifiedFilestorageFileInput) GetFolderID() string {
	if o == nil {
		return ""
	}
	return o.FolderID
}

func (o *UnifiedFilestorageFileInput) GetPermission() string {
	if o == nil {
		return ""
	}
	return o.Permission
}

func (o *UnifiedFilestorageFileInput) GetSharedLink() string {
	if o == nil {
		return ""
	}
	return o.SharedLink
}

func (o *UnifiedFilestorageFileInput) GetFieldMappings() UnifiedFilestorageFileInputFieldMappings {
	if o == nil {
		return UnifiedFilestorageFileInputFieldMappings{}
	}
	return o.FieldMappings
}
