// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

// UnifiedCrmEngagementInputDirection - The direction of the engagement. Authorized values are INBOUND or OUTBOUND
type UnifiedCrmEngagementInputDirection string

const (
	UnifiedCrmEngagementInputDirectionInbound  UnifiedCrmEngagementInputDirection = "INBOUND"
	UnifiedCrmEngagementInputDirectionOutbound UnifiedCrmEngagementInputDirection = "OUTBOUND"
)

func (e UnifiedCrmEngagementInputDirection) ToPointer() *UnifiedCrmEngagementInputDirection {
	return &e
}
func (e *UnifiedCrmEngagementInputDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INBOUND":
		fallthrough
	case "OUTBOUND":
		*e = UnifiedCrmEngagementInputDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnifiedCrmEngagementInputDirection: %v", v)
	}
}

// UnifiedCrmEngagementInputType - The type of the engagement. Authorized values are EMAIL, CALL or MEETING
type UnifiedCrmEngagementInputType string

const (
	UnifiedCrmEngagementInputTypeEmail   UnifiedCrmEngagementInputType = "EMAIL"
	UnifiedCrmEngagementInputTypeCall    UnifiedCrmEngagementInputType = "CALL"
	UnifiedCrmEngagementInputTypeMeeting UnifiedCrmEngagementInputType = "MEETING"
)

func (e UnifiedCrmEngagementInputType) ToPointer() *UnifiedCrmEngagementInputType {
	return &e
}
func (e *UnifiedCrmEngagementInputType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EMAIL":
		fallthrough
	case "CALL":
		fallthrough
	case "MEETING":
		*e = UnifiedCrmEngagementInputType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnifiedCrmEngagementInputType: %v", v)
	}
}

type UnifiedCrmEngagementInput struct {
	// The content of the engagement
	Content *string `json:"content,omitempty"`
	// The direction of the engagement. Authorized values are INBOUND or OUTBOUND
	Direction *UnifiedCrmEngagementInputDirection `json:"direction,omitempty"`
	// The subject of the engagement
	Subject *string `json:"subject,omitempty"`
	// The start time of the engagement
	StartAt *time.Time `json:"start_at,omitempty"`
	// The end time of the engagement
	EndTime *time.Time `json:"end_time,omitempty"`
	// The type of the engagement. Authorized values are EMAIL, CALL or MEETING
	Type *UnifiedCrmEngagementInputType `json:"type"`
	// The UUID of the user tied to the engagement
	UserID *string `json:"user_id,omitempty"`
	// The UUID of the company tied to the engagement
	CompanyID *string `json:"company_id,omitempty"`
	// The UUIDs of contacts tied to the engagement object
	Contacts []string `json:"contacts,omitempty"`
	// The custom field mappings of the engagement between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
}

func (u UnifiedCrmEngagementInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedCrmEngagementInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedCrmEngagementInput) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *UnifiedCrmEngagementInput) GetDirection() *UnifiedCrmEngagementInputDirection {
	if o == nil {
		return nil
	}
	return o.Direction
}

func (o *UnifiedCrmEngagementInput) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *UnifiedCrmEngagementInput) GetStartAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartAt
}

func (o *UnifiedCrmEngagementInput) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *UnifiedCrmEngagementInput) GetType() *UnifiedCrmEngagementInputType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *UnifiedCrmEngagementInput) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *UnifiedCrmEngagementInput) GetCompanyID() *string {
	if o == nil {
		return nil
	}
	return o.CompanyID
}

func (o *UnifiedCrmEngagementInput) GetContacts() []string {
	if o == nil {
		return nil
	}
	return o.Contacts
}

func (o *UnifiedCrmEngagementInput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}
