// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedAtsOfficeOutputFieldMappings struct {
}

type UnifiedAtsOfficeOutputRemoteData struct {
}

type UnifiedAtsOfficeOutputCreatedAt struct {
}

type UnifiedAtsOfficeOutputModifiedAt struct {
}

type UnifiedAtsOfficeOutput struct {
	// The name of the office
	Name *string `json:"name,omitempty"`
	// The location of the office
	Location      *string                             `json:"location,omitempty"`
	FieldMappings UnifiedAtsOfficeOutputFieldMappings `json:"field_mappings"`
	// The UUID of the office
	ID *string `json:"id,omitempty"`
	// The remote ID of the office in the context of the 3rd Party
	RemoteID   *string                          `json:"remote_id,omitempty"`
	RemoteData UnifiedAtsOfficeOutputRemoteData `json:"remote_data"`
	CreatedAt  UnifiedAtsOfficeOutputCreatedAt  `json:"created_at"`
	ModifiedAt UnifiedAtsOfficeOutputModifiedAt `json:"modified_at"`
}

func (o *UnifiedAtsOfficeOutput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnifiedAtsOfficeOutput) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *UnifiedAtsOfficeOutput) GetFieldMappings() UnifiedAtsOfficeOutputFieldMappings {
	if o == nil {
		return UnifiedAtsOfficeOutputFieldMappings{}
	}
	return o.FieldMappings
}

func (o *UnifiedAtsOfficeOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedAtsOfficeOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedAtsOfficeOutput) GetRemoteData() UnifiedAtsOfficeOutputRemoteData {
	if o == nil {
		return UnifiedAtsOfficeOutputRemoteData{}
	}
	return o.RemoteData
}

func (o *UnifiedAtsOfficeOutput) GetCreatedAt() UnifiedAtsOfficeOutputCreatedAt {
	if o == nil {
		return UnifiedAtsOfficeOutputCreatedAt{}
	}
	return o.CreatedAt
}

func (o *UnifiedAtsOfficeOutput) GetModifiedAt() UnifiedAtsOfficeOutputModifiedAt {
	if o == nil {
		return UnifiedAtsOfficeOutputModifiedAt{}
	}
	return o.ModifiedAt
}
