// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

// UnifiedHrisEmployerbenefitOutputFieldMappings - The custom field mappings of the object between the remote 3rd party & Panora
type UnifiedHrisEmployerbenefitOutputFieldMappings struct {
}

// UnifiedHrisEmployerbenefitOutputRemoteData - The remote data of the employer benefit in the context of the 3rd Party
type UnifiedHrisEmployerbenefitOutputRemoteData struct {
}

type UnifiedHrisEmployerbenefitOutput struct {
	// The type of the benefit plan
	BenefitPlanType *string `json:"benefit_plan_type,omitempty"`
	// The name of the employer benefit
	Name *string `json:"name,omitempty"`
	// The description of the employer benefit
	Description *string `json:"description,omitempty"`
	// The deduction code for the employer benefit
	DeductionCode *string `json:"deduction_code,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings *UnifiedHrisEmployerbenefitOutputFieldMappings `json:"field_mappings,omitempty"`
	// The UUID of the employer benefit record
	ID *string `json:"id,omitempty"`
	// The remote ID of the employer benefit in the context of the 3rd Party
	RemoteID *string `json:"remote_id,omitempty"`
	// The remote data of the employer benefit in the context of the 3rd Party
	RemoteData *UnifiedHrisEmployerbenefitOutputRemoteData `json:"remote_data,omitempty"`
	// The date when the employer benefit was created in the 3rd party system
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The created date of the employer benefit record
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The last modified date of the employer benefit record
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// Indicates if the employer benefit was deleted in the remote system
	RemoteWasDeleted *bool `json:"remote_was_deleted,omitempty"`
}

func (u UnifiedHrisEmployerbenefitOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedHrisEmployerbenefitOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedHrisEmployerbenefitOutput) GetBenefitPlanType() *string {
	if o == nil {
		return nil
	}
	return o.BenefitPlanType
}

func (o *UnifiedHrisEmployerbenefitOutput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnifiedHrisEmployerbenefitOutput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UnifiedHrisEmployerbenefitOutput) GetDeductionCode() *string {
	if o == nil {
		return nil
	}
	return o.DeductionCode
}

func (o *UnifiedHrisEmployerbenefitOutput) GetFieldMappings() *UnifiedHrisEmployerbenefitOutputFieldMappings {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *UnifiedHrisEmployerbenefitOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedHrisEmployerbenefitOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedHrisEmployerbenefitOutput) GetRemoteData() *UnifiedHrisEmployerbenefitOutputRemoteData {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *UnifiedHrisEmployerbenefitOutput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedHrisEmployerbenefitOutput) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UnifiedHrisEmployerbenefitOutput) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *UnifiedHrisEmployerbenefitOutput) GetRemoteWasDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.RemoteWasDeleted
}
