// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type UnifiedTicketingAccountOutput struct {
	// The name of the account
	Name *string `json:"name"`
	// The domains of the account
	Domains []string `json:"domains,omitempty"`
	// The custom field mappings of the account between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
	// The UUID of the account
	ID *string `json:"id,omitempty"`
	// The remote ID of the account in the context of the 3rd Party
	RemoteID *string `json:"remote_id,omitempty"`
	// The remote data of the account in the context of the 3rd Party
	RemoteData map[string]any `json:"remote_data,omitempty"`
	// The created date of the account
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The modified date of the account
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
}

func (u UnifiedTicketingAccountOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedTicketingAccountOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedTicketingAccountOutput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnifiedTicketingAccountOutput) GetDomains() []string {
	if o == nil {
		return nil
	}
	return o.Domains
}

func (o *UnifiedTicketingAccountOutput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *UnifiedTicketingAccountOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedTicketingAccountOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedTicketingAccountOutput) GetRemoteData() map[string]any {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *UnifiedTicketingAccountOutput) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UnifiedTicketingAccountOutput) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}
