// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type UnifiedAtsAttachmentInputFieldMappings struct {
}

type UnifiedAtsAttachmentInput struct {
	// The URL of the file
	FileURL *string `json:"file_url,omitempty"`
	// The name of the file
	FileName *string `json:"file_name,omitempty"`
	// The type of the file
	AttachmentType *string `json:"attachment_type,omitempty"`
	// The remote creation date of the attachment
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The remote modification date of the attachment
	RemoteModifiedAt *time.Time `json:"remote_modified_at,omitempty"`
	// The UUID of the candidate
	CandidateID   *string                                `json:"candidate_id,omitempty"`
	FieldMappings UnifiedAtsAttachmentInputFieldMappings `json:"field_mappings"`
}

func (u UnifiedAtsAttachmentInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedAtsAttachmentInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedAtsAttachmentInput) GetFileURL() *string {
	if o == nil {
		return nil
	}
	return o.FileURL
}

func (o *UnifiedAtsAttachmentInput) GetFileName() *string {
	if o == nil {
		return nil
	}
	return o.FileName
}

func (o *UnifiedAtsAttachmentInput) GetAttachmentType() *string {
	if o == nil {
		return nil
	}
	return o.AttachmentType
}

func (o *UnifiedAtsAttachmentInput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedAtsAttachmentInput) GetRemoteModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteModifiedAt
}

func (o *UnifiedAtsAttachmentInput) GetCandidateID() *string {
	if o == nil {
		return nil
	}
	return o.CandidateID
}

func (o *UnifiedAtsAttachmentInput) GetFieldMappings() UnifiedAtsAttachmentInputFieldMappings {
	if o == nil {
		return UnifiedAtsAttachmentInputFieldMappings{}
	}
	return o.FieldMappings
}
