// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/go-sdk/internal/utils"
	"time"
)

type UnifiedAtsInterviewOutput struct {
	// The status of the interview
	Status *string `json:"status,omitempty"`
	// The UUID of the application
	ApplicationID *string `json:"application_id,omitempty"`
	// The UUID of the job interview stage
	JobInterviewStageID *string `json:"job_interview_stage_id,omitempty"`
	// The UUID of the organizer
	OrganizedBy *string `json:"organized_by,omitempty"`
	// The UUIDs of the interviewers
	Interviewers []string `json:"interviewers,omitempty"`
	// The location of the interview
	Location *string `json:"location,omitempty"`
	// The start date and time of the interview
	StartAt *time.Time `json:"start_at,omitempty"`
	// The end date and time of the interview
	EndAt *time.Time `json:"end_at,omitempty"`
	// The remote creation date of the interview
	RemoteCreatedAt *time.Time `json:"remote_created_at,omitempty"`
	// The remote modification date of the interview
	RemoteUpdatedAt *time.Time `json:"remote_updated_at,omitempty"`
	// The custom field mappings of the object between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings,omitempty"`
	// The UUID of the interview
	ID *string `json:"id,omitempty"`
	// The remote ID of the interview in the context of the 3rd Party
	RemoteID *string `json:"remote_id,omitempty"`
	// The remote data of the interview in the context of the 3rd Party
	RemoteData map[string]any `json:"remote_data,omitempty"`
	// The created date of the object
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The modified date of the object
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
}

func (u UnifiedAtsInterviewOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnifiedAtsInterviewOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnifiedAtsInterviewOutput) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UnifiedAtsInterviewOutput) GetApplicationID() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationID
}

func (o *UnifiedAtsInterviewOutput) GetJobInterviewStageID() *string {
	if o == nil {
		return nil
	}
	return o.JobInterviewStageID
}

func (o *UnifiedAtsInterviewOutput) GetOrganizedBy() *string {
	if o == nil {
		return nil
	}
	return o.OrganizedBy
}

func (o *UnifiedAtsInterviewOutput) GetInterviewers() []string {
	if o == nil {
		return nil
	}
	return o.Interviewers
}

func (o *UnifiedAtsInterviewOutput) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *UnifiedAtsInterviewOutput) GetStartAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartAt
}

func (o *UnifiedAtsInterviewOutput) GetEndAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndAt
}

func (o *UnifiedAtsInterviewOutput) GetRemoteCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteCreatedAt
}

func (o *UnifiedAtsInterviewOutput) GetRemoteUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RemoteUpdatedAt
}

func (o *UnifiedAtsInterviewOutput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}

func (o *UnifiedAtsInterviewOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedAtsInterviewOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedAtsInterviewOutput) GetRemoteData() map[string]any {
	if o == nil {
		return nil
	}
	return o.RemoteData
}

func (o *UnifiedAtsInterviewOutput) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UnifiedAtsInterviewOutput) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}
