// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedAtsDepartmentOutputFieldMappings struct {
}

type UnifiedAtsDepartmentOutputRemoteData struct {
}

type UnifiedAtsDepartmentOutputCreatedAt struct {
}

type UnifiedAtsDepartmentOutputModifiedAt struct {
}

type UnifiedAtsDepartmentOutput struct {
	// The name of the department
	Name          *string                                 `json:"name,omitempty"`
	FieldMappings UnifiedAtsDepartmentOutputFieldMappings `json:"field_mappings"`
	// The UUID of the department
	ID *string `json:"id,omitempty"`
	// The remote ID of the department in the context of the 3rd Party
	RemoteID   *string                              `json:"remote_id,omitempty"`
	RemoteData UnifiedAtsDepartmentOutputRemoteData `json:"remote_data"`
	CreatedAt  UnifiedAtsDepartmentOutputCreatedAt  `json:"created_at"`
	ModifiedAt UnifiedAtsDepartmentOutputModifiedAt `json:"modified_at"`
}

func (o *UnifiedAtsDepartmentOutput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnifiedAtsDepartmentOutput) GetFieldMappings() UnifiedAtsDepartmentOutputFieldMappings {
	if o == nil {
		return UnifiedAtsDepartmentOutputFieldMappings{}
	}
	return o.FieldMappings
}

func (o *UnifiedAtsDepartmentOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UnifiedAtsDepartmentOutput) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *UnifiedAtsDepartmentOutput) GetRemoteData() UnifiedAtsDepartmentOutputRemoteData {
	if o == nil {
		return UnifiedAtsDepartmentOutputRemoteData{}
	}
	return o.RemoteData
}

func (o *UnifiedAtsDepartmentOutput) GetCreatedAt() UnifiedAtsDepartmentOutputCreatedAt {
	if o == nil {
		return UnifiedAtsDepartmentOutputCreatedAt{}
	}
	return o.CreatedAt
}

func (o *UnifiedAtsDepartmentOutput) GetModifiedAt() UnifiedAtsDepartmentOutputModifiedAt {
	if o == nil {
		return UnifiedAtsDepartmentOutputModifiedAt{}
	}
	return o.ModifiedAt
}
