// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnifiedTicketingAttachmentInput struct {
	// The file name of the attachment
	FileName *string `json:"file_name"`
	// The file url of the attachment
	FileURL *string `json:"file_url"`
	// The uploader's UUID of the attachment
	Uploader *string `json:"uploader"`
	// The UUID of the ticket the attachment is tied to
	TicketID *string `json:"ticket_id,omitempty"`
	// The UUID of the comment the attachment is tied to
	CommentID *string `json:"comment_id,omitempty"`
	// The custom field mappings of the attachment between the remote 3rd party & Panora
	FieldMappings map[string]any `json:"field_mappings"`
}

func (o *UnifiedTicketingAttachmentInput) GetFileName() *string {
	if o == nil {
		return nil
	}
	return o.FileName
}

func (o *UnifiedTicketingAttachmentInput) GetFileURL() *string {
	if o == nil {
		return nil
	}
	return o.FileURL
}

func (o *UnifiedTicketingAttachmentInput) GetUploader() *string {
	if o == nil {
		return nil
	}
	return o.Uploader
}

func (o *UnifiedTicketingAttachmentInput) GetTicketID() *string {
	if o == nil {
		return nil
	}
	return o.TicketID
}

func (o *UnifiedTicketingAttachmentInput) GetCommentID() *string {
	if o == nil {
		return nil
	}
	return o.CommentID
}

func (o *UnifiedTicketingAttachmentInput) GetFieldMappings() map[string]any {
	if o == nil {
		return nil
	}
	return o.FieldMappings
}
