// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdatePullFrequencyDto struct {
	// Frequency in seconds
	Crm float64 `json:"crm"`
	// Frequency in seconds
	Accounting float64 `json:"accounting"`
	// Frequency in seconds
	Filestorage float64 `json:"filestorage"`
	// Frequency in seconds
	Ecommerce float64 `json:"ecommerce"`
	// Frequency in seconds
	Ticketing float64 `json:"ticketing"`
}

func (o *UpdatePullFrequencyDto) GetCrm() float64 {
	if o == nil {
		return 0.0
	}
	return o.Crm
}

func (o *UpdatePullFrequencyDto) GetAccounting() float64 {
	if o == nil {
		return 0.0
	}
	return o.Accounting
}

func (o *UpdatePullFrequencyDto) GetFilestorage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Filestorage
}

func (o *UpdatePullFrequencyDto) GetEcommerce() float64 {
	if o == nil {
		return 0.0
	}
	return o.Ecommerce
}

func (o *UpdatePullFrequencyDto) GetTicketing() float64 {
	if o == nil {
		return 0.0
	}
	return o.Ticketing
}
